#!/usr/bin/env node
'use strict';
/**
 * rtx.js — RealTimeX SDK CLI (source-verified)
 * AUTO-GENERATED by scripts/generate-skill.mjs — do not edit by hand.
 *
 * All method signatures derived from the @realtimex/sdk TypeScript source.
 *
 * Usage: node rtx.js <command> [args...] [--flags]
 * Global flags:
 *   --api-key=<key>    Override API key
 *   --env-dir=<path>   Directory containing .env (default: cwd)
 *   --url=<url>        RealTimeX server URL (default: http://localhost:3001)
 */

const path = require('path');
const { initSDK } = require('./lib/sdk-init');

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------
function parseArgs(argv) {
  const flags = {}, positional = [];
  for (const arg of argv) {
    if (arg.startsWith('--')) {
      const [k, ...rest] = arg.slice(2).split('=');
      flags[k] = rest.length ? rest.join('=') : true;
    } else { positional.push(arg); }
  }
  return { flags, positional };
}
const { flags, positional } = parseArgs(process.argv.slice(2));
const [command, ...cmdArgs] = positional;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function print(obj) { console.log(JSON.stringify(obj, null, 2)); }
function printTable(rows, cols) {
  if (!rows?.length) { console.log('(no results)'); return; }
  const keys = cols || Object.keys(rows[0]);
  const widths = keys.map(k => Math.max(k.length, ...rows.map(r => String(r[k] ?? '').length)));
  const pad = (s, w) => String(s ?? '').padEnd(w);
  console.log(keys.map((k, i) => pad(k, widths[i])).join('  '));
  console.log(widths.map(w => '-'.repeat(w)).join('  '));
  for (const r of rows) console.log(keys.map((k, i) => pad(r[k], widths[i])).join('  '));
}

let _sdk = null;
async function getSDK() {
  if (_sdk) return _sdk;
  _sdk = await initSDK({ envDir: flags['env-dir'] || process.cwd(), apiKey: flags['api-key'], url: flags['url'] });
  return _sdk;
}

function applyWorkspaceThreadDefaults(body = {}, context = {}) {
  const nextBody = { ...body };
  if (!nextBody.workspaceSlug && context?.workspaceSlug) {
    nextBody.workspaceSlug = context.workspaceSlug;
  }
  if (!nextBody.threadSlug && context?.threadSlug) {
    nextBody.threadSlug = context.threadSlug;
  }
  return nextBody;
}

function resolveWorkspaceFlagOrContext(context = {}) {
  return flags.workspace || context?.workspaceSlug || null;
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------
const CMD = {};

CMD.context = async () => {
  const { context } = await getSDK();
  print({
    workspaceSlug: context?.workspaceSlug || null,
    threadSlug: context?.threadSlug || null,
    hasContext: Boolean(context?.workspaceSlug || context?.threadSlug),
  });
};

// -- ping -------------------------------------------------------------------
// Source: index.ts → sdk.ping() → { success, mode, appId, timestamp }
CMD.ping = async () => { const { sdk } = await getSDK(); print(await sdk.ping()); };

// -- info -------------------------------------------------------------------
CMD.info = async () => {
  const { sdk, apiKey } = await getSDK();
  console.log('API key: ' + apiKey.slice(0, 8) + '...');
  try { console.log('Data dir: ' + await sdk.getAppDataDir()); } catch (_) {}
  print(await sdk.ping());
};

// -- agents -----------------------------------------------------------------
// Source: modules/api.ts → ApiModule.getAgents() → Agent[]
// Agent: { slug, name, description?, hub_id? }
// NOTE: on sdk.api, NOT sdk directly
CMD.agents = async () => {
  const { sdk } = await getSDK();
  printTable(await sdk.api.getAgents(), ['slug', 'name', 'description']);
};

// -- workspaces -------------------------------------------------------------
// Source: ApiModule.getWorkspaces() → Workspace[] { id, slug, name, type }
CMD.workspaces = async () => {
  const { sdk } = await getSDK();
  printTable(await sdk.api.getWorkspaces(), ['id', 'slug', 'name', 'type']);
};

// -- threads ----------------------------------------------------------------
// Source: ApiModule.getThreads(workspaceSlug) → Thread[] { id, slug, name }
CMD.threads = async () => {
  const [slugArg] = cmdArgs;
  const { sdk, context } = await getSDK();
  const slug = slugArg || resolveWorkspaceFlagOrContext(context);
  if (!slug) { console.error('Usage: rtx.js threads <workspace-slug>'); process.exit(1); }
  printTable(await sdk.api.getThreads(slug), ['id', 'slug', 'name']);
};

// -- task -------------------------------------------------------------------
// Source: ApiModule.getTask(taskUuid) → Task { uuid, title, status, ..., runs }
CMD.task = async () => {
  const [uuid] = cmdArgs;
  if (!uuid) { console.error('Usage: rtx.js task <uuid>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.api.getTask(uuid));
};

// -- activities -------------------------------------------------------------
// Source: ActivitiesModule.list(options?) → Activity[]  (direct array, NOT { activities: [...] })
CMD.activities = async () => {
  const { sdk } = await getSDK();
  const opts = {};
  if (flags.status) opts.status = flags.status;
  if (flags.limit)  opts.limit  = Number(flags.limit);
  if (flags.offset) opts.offset = Number(flags.offset);
  print(await sdk.activities.list(opts));
};

// -- activity-get -----------------------------------------------------------
// Source: ActivitiesModule.get(id) → Activity | null
CMD['activity-get'] = async () => {
  const [id] = cmdArgs;
  if (!id) { console.error('Usage: rtx.js activity-get <id>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.activities.get(id));
};

// -- activity-create --------------------------------------------------------
// Source: ActivitiesModule.insert(rawData: Record<string,unknown>) → Activity
// rawData is your payload; SDK wraps it in { raw_data: rawData } automatically.
CMD['activity-create'] = async () => {
  const [jsonStr] = cmdArgs;
  if (!jsonStr) { console.error('Usage: rtx.js activity-create <json-payload>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.activities.insert(JSON.parse(jsonStr)));
};

// -- activity-update --------------------------------------------------------
// Source: ActivitiesModule.update(id, updates: Partial<Activity>) → Activity
CMD['activity-update'] = async () => {
  const [id, jsonStr] = cmdArgs;
  if (!id || !jsonStr) { console.error('Usage: rtx.js activity-update <id> <json-updates>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.activities.update(id, JSON.parse(jsonStr)));
};

// -- activity-delete --------------------------------------------------------
// Source: ActivitiesModule.delete(id) → void
CMD['activity-delete'] = async () => {
  const [id] = cmdArgs;
  if (!id) { console.error('Usage: rtx.js activity-delete <id>'); process.exit(1); }
  const { sdk } = await getSDK();
  await sdk.activities.delete(id);
  console.log('Deleted.');
};

// -- task-start / task-complete / task-fail ---------------------------------
// Source: modules/task.ts
// CORRECT signatures (positional, NOT { task_uuid } object):
//   start(taskUuid, machineIdOrOptions?)
//   complete(taskUuid, result?, machineIdOrOptions?)
//   fail(taskUuid, error: string, machineIdOrOptions?)
CMD['task-start'] = async () => {
  const [uuid] = cmdArgs;
  if (!uuid) { console.error('Usage: rtx.js task-start <uuid> [--machine=<id>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.task.start(uuid, flags.machine ? { machineId: flags.machine } : undefined));
};
CMD['task-complete'] = async () => {
  const [uuid, resultStr] = cmdArgs;
  if (!uuid) { console.error('Usage: rtx.js task-complete <uuid> [<result-json>] [--machine=<id>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.task.complete(uuid, resultStr ? JSON.parse(resultStr) : {}, flags.machine ? { machineId: flags.machine } : undefined));
};
CMD['task-fail'] = async () => {
  const [uuid, ...errParts] = cmdArgs;
  const errMsg = errParts.join(' ');
  if (!uuid || !errMsg) { console.error('Usage: rtx.js task-fail <uuid> <error-message>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.task.fail(uuid, errMsg, flags.machine ? { machineId: flags.machine } : undefined));
};
CMD['task-progress'] = async () => {
  const [uuid, dataStr] = cmdArgs;
  if (!uuid) { console.error('Usage: rtx.js task-progress <uuid> [<progress-json>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.task.progress(uuid, dataStr ? JSON.parse(dataStr) : {}));
};
CMD['task-cancel'] = async () => {
  const [uuid, ...reasonParts] = cmdArgs;
  if (!uuid) { console.error('Usage: rtx.js task-cancel <uuid> [<reason>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.task.cancel(uuid, reasonParts.join(' ') || undefined));
};

// -- trigger-agent ----------------------------------------------------------
// IMPORTANT: sdk.webhook.triggerAgent() sends event "task.trigger" which the
// server rejects (expects "trigger-agent"). This command bypasses the SDK
// method and uses a direct fetch call with the correct event string.
// Source evidence: modules/webhook.ts hardcodes event: 'task.trigger'
//                  server/endpoints/sdk/webhook.js enum: ['trigger-agent',...]
CMD['trigger-agent'] = async () => {
  const [agentName, workspaceSlug, ...promptParts] = cmdArgs;
  const prompt = promptParts.join(' ');
  if (!agentName || !workspaceSlug || !prompt) {
    console.error('Usage: rtx.js trigger-agent <agent-name> <workspace-slug> <prompt> [--thread=<slug>] [--data=<json>]');
    process.exit(1);
  }
  const { apiKey } = await getSDK();
  const resp = await fetch('http://localhost:3001/webhooks/realtimex', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + apiKey },
    body: JSON.stringify({
      event: 'trigger-agent',
      payload: {
        auto_run: true,
        agent_name: agentName,
        workspace_slug: workspaceSlug,
        thread_slug: flags.thread || undefined,
        prompt,
        raw_data: flags.data ? JSON.parse(flags.data) : {},
      },
    }),
  });
  print(await resp.json());
};

// -- webhook-ping -----------------------------------------------------------
// Source: WebhookModule.ping() → sends event: 'system.ping' (accepted by server)
CMD['webhook-ping'] = async () => {
  const { sdk } = await getSDK();
  print(await sdk.webhook.ping());
};

// -- llm-providers ----------------------------------------------------------
// Source: LLMModule.chatProviders() → { success, providers: [{ provider, models }] }
CMD['llm-providers'] = async () => {
  const { sdk } = await getSDK();
  const { providers } = await sdk.llm.chatProviders();
  for (const p of (providers || [])) {
    console.log('\nProvider: ' + p.provider);
    if (p.models?.length) printTable(p.models, ['id', 'name']);
  }
};
CMD['embed-providers'] = async () => {
  const { sdk } = await getSDK();
  const { providers } = await sdk.llm.embedProviders();
  for (const p of (providers || [])) {
    console.log('\nProvider: ' + p.provider);
    if (p.models?.length) printTable(p.models, ['id', 'name']);
  }
};

// -- llm-chat ---------------------------------------------------------------
// Source: LLMModule.chat() → ChatResponse { success, response?: { content, model, metrics } }
// Access text via res.response?.content  (NOT choices[0].message.content)
// Stream: yields StreamChunk { textResponse?, close?, error? }  (NOT delta.content)
CMD['llm-chat'] = async () => {
  const message = cmdArgs.join(' ');
  if (!message) { console.error('Usage: rtx.js llm-chat <message> [--stream] [--model=<m>] [--provider=<p>]'); process.exit(1); }
  const { sdk } = await getSDK();
  const opts = {};
  if (flags.model)    opts.model    = flags.model;
  if (flags.provider) opts.provider = flags.provider;
  if (flags.stream) {
    for await (const chunk of sdk.llm.chatStream([{ role: 'user', content: message }], opts)) {
      if (chunk.textResponse) process.stdout.write(chunk.textResponse);
      if (chunk.close) break;
    }
    process.stdout.write('\n');
  } else {
    const res = await sdk.llm.chat([{ role: 'user', content: message }], opts);
    console.log(res.response?.content ?? res.error ?? JSON.stringify(res));
  }
};

// -- llm-embed --------------------------------------------------------------
// Source: LLMModule.embed(input: string | string[], options?)
// Returns: EmbedResponse { success, embeddings: number[][], model, dimensions }
CMD['llm-embed'] = async () => {
  const text = cmdArgs.join(' ');
  if (!text) { console.error('Usage: rtx.js llm-embed <text> [--model=<m>]'); process.exit(1); }
  const { sdk } = await getSDK();
  const res = await sdk.llm.embed(text, { model: flags.model, provider: flags.provider });
  console.log('success: ' + res.success + ', model: ' + res.model + ', dimensions: ' + res.dimensions);
  if (flags.vectors && res.embeddings?.[0]) print(res.embeddings[0].slice(0, 10));
};

// -- mcp-servers ------------------------------------------------------------
// Source: MCPModule.getServers(provider?: 'local'|'remote'|'all')
// CORRECT: plain string arg, NOT { provider: 'all' }
CMD['mcp-servers'] = async () => {
  const { sdk } = await getSDK();
  printTable(await sdk.mcp.getServers(flags.provider || 'all'), ['name', 'provider', 'status']);
};
CMD['mcp-tools'] = async () => {
  const [name] = cmdArgs;
  if (!name) { console.error('Usage: rtx.js mcp-tools <server-name> [--provider=local|remote]'); process.exit(1); }
  const { sdk } = await getSDK();
  printTable(await sdk.mcp.getTools(name, flags.provider), ['name', 'description']);
};
CMD['mcp-exec'] = async () => {
  const [server, tool, argsStr] = cmdArgs;
  if (!server || !tool) { console.error('Usage: rtx.js mcp-exec <server> <tool> [<args-json>] [--provider=local|remote]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.mcp.executeTool(server, tool, argsStr ? JSON.parse(argsStr) : {}, flags.provider));
};

// -- credentials ------------------------------------------------------------
CMD['credentials'] = async () => {
  const { sdk } = await getSDK();
  const list = await sdk.credentials.list();
  printTable(list, ['name', 'type']);
};

function getDesktopRuntimeSessionsModule(sdk) {
  const module = sdk?.desktopRuntimeSessions || sdk?.v1?.desktopRuntimeSessions;
  if (!module) {
    throw new Error('sdk.desktopRuntimeSessions is unavailable. Ensure the SDK was initialized with Developer API access.');
  }
  return module;
}

function getDesktopBrowserModule(sdk) {
  const module = sdk?.desktopBrowser || sdk?.v1?.desktopBrowser;
  if (!module) {
    throw new Error('sdk.desktopBrowser is unavailable. Ensure the SDK was initialized with Developer API access.');
  }
  return module;
}

// -- terminal-launcher / terminal sessions ----------------------------------
CMD['terminal-open-launcher'] = async () => {
  const { sdk, context } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const body = applyWorkspaceThreadDefaults({}, context);
  if (flags.workspace) body.workspaceSlug = flags.workspace;
  if (flags.thread) body.threadSlug = flags.thread;
  if (flags.presentation) body.presentationMode = flags.presentation;
  if (flags.agent) body.preferredAgentName = flags.agent;
  if (flags.provider) body.preferredAgentProviderId = flags.provider;
  print(await terminal.openLauncher(body));
};

CMD['terminal-launch-shell'] = async () => {
  const { sdk, context } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const body = applyWorkspaceThreadDefaults({}, context);
  if (flags.workspace) body.workspaceSlug = flags.workspace;
  if (flags.thread) body.threadSlug = flags.thread;
  if (flags.presentation) body.presentationMode = flags.presentation;
  if (flags.command) body.initialCommand = flags.command;
  if (flags['command-mode']) {
    body.initialCommandMode = flags['command-mode'];
  } else if (flags.command) {
    body.initialCommandMode = 'direct';
  }
  if (flags.title) body.title = flags.title;
  if (flags.subtitle) body.subtitle = flags.subtitle;
  print(await terminal.launchTerminalShell(body));
};

CMD['terminal-launch-cli-agent'] = async () => {
  const [agentName, providerId, ...messageParts] = cmdArgs;
  const message = messageParts.join(' ');
  if (!agentName) {
    console.error('Usage: rtx.js terminal-launch-cli-agent <agent-name> [<provider-id>] [<message>] [--workspace=<slug>] [--thread=<slug>] [--presentation=panel|tab] [--model=<id>]');
    process.exit(1);
  }
  const { sdk, context } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const body = applyWorkspaceThreadDefaults({ agentName }, context);
  if (providerId) body.providerId = providerId;
  if (message) body.message = message;
  if (flags.workspace) body.workspaceSlug = flags.workspace;
  if (flags.thread) body.threadSlug = flags.thread;
  if (flags.presentation) body.presentationMode = flags.presentation;
  if (flags.model) body.modelId = flags.model;
  print(await terminal.launchTerminalCliAgent(body));
};

CMD['terminal-sessions'] = async () => {
  const { sdk } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const sessions = await terminal.listRuntimeSessions();
  print(sessions);
};

CMD['terminal-session-get'] = async () => {
  const [sessionId] = cmdArgs;
  if (!sessionId) {
    console.error('Usage: rtx.js terminal-session-get <session-id>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  print(await terminal.getRuntimeSession(sessionId));
};

CMD['terminal-write'] = async () => {
  const [sessionId, ...rest] = cmdArgs;
  if (!sessionId || rest.length === 0) {
    console.error('Usage: rtx.js terminal-write <session-id> <message> [--raw]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const payload = rest.join(' ');
  print(await terminal.write(sessionId, flags.raw ? { input: payload } : { message: payload }));
};

CMD['terminal-permission'] = async () => {
  const [sessionId, outcome, actionId] = cmdArgs;
  if (!sessionId || !outcome) {
    console.error('Usage: rtx.js terminal-permission <session-id> <approved|denied> [<action-id>] [--option-id=<id>] [--reason=<text>]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  const body = { outcome };
  if (actionId) body.actionId = actionId;
  if (flags['option-id']) body.optionId = flags['option-id'];
  if (flags.reason) body.reason = flags.reason;
  print(await terminal.permission(sessionId, body));
};

CMD['terminal-close'] = async () => {
  const [sessionId] = cmdArgs;
  if (!sessionId) {
    console.error('Usage: rtx.js terminal-close <session-id>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const terminal = getDesktopRuntimeSessionsModule(sdk);
  print(await terminal.deleteRuntimeSession(sessionId));
};

CMD['browser-sessions'] = async () => {
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  print(await browser.listSessions());
};

CMD['browser-session-create'] = async () => {
  const [sessionName] = cmdArgs;
  if (!sessionName) {
    console.error('Usage: rtx.js browser-session-create <session-name> [--port=<n>]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  const body = {
    sessionName,
    ...(flags.port ? { remoteDebugPort: Number(flags.port) } : {}),
  };
  print(await browser.createSession(body));
};

CMD['browser-session-get'] = async () => {
  const [sessionName] = cmdArgs;
  if (!sessionName) {
    console.error('Usage: rtx.js browser-session-get <session-name>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  print(await browser.getSession(sessionName));
};

CMD['browser-session-delete'] = async () => {
  const [sessionName] = cmdArgs;
  if (!sessionName) {
    console.error('Usage: rtx.js browser-session-delete <session-name>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  print(await browser.deleteSession(sessionName));
};

CMD['browser-tab-create'] = async () => {
  const [url] = cmdArgs;
  if (!url) {
    console.error('Usage: rtx.js browser-tab-create <url> [--session=<name>] [--focus=true|false] [--focus-window=true|false]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  const body = {
    url,
    ...(flags.session ? { sessionName: flags.session } : {}),
    ...(flags.focus !== undefined ? { focus: flags.focus !== 'false' } : {}),
    ...(flags['focus-window'] !== undefined ? { focusWindow: flags['focus-window'] !== 'false' } : {}),
  };
  print(await browser.createTab(body));
};

CMD['browser-tab-get'] = async () => {
  const [tabRef] = cmdArgs;
  if (!tabRef) {
    console.error('Usage: rtx.js browser-tab-get <tab-ref>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  print(await browser.getTab(tabRef));
};

CMD['browser-tab-focus'] = async () => {
  const [tabRef] = cmdArgs;
  if (!tabRef) {
    console.error('Usage: rtx.js browser-tab-focus <tab-ref> [--focus-window=true|false]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  const body = flags['focus-window'] !== undefined ? { focusWindow: flags['focus-window'] !== 'false' } : {};
  print(await browser.focusTab(tabRef, body));
};

CMD['browser-tab-navigate'] = async () => {
  const [tabRef, url] = cmdArgs;
  if (!tabRef || !url) {
    console.error('Usage: rtx.js browser-tab-navigate <tab-ref> <url> [--focus=true|false] [--focus-window=true|false]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  const body = {
    url,
    ...(flags.focus !== undefined ? { focus: flags.focus !== 'false' } : {}),
    ...(flags['focus-window'] !== undefined ? { focusWindow: flags['focus-window'] !== 'false' } : {}),
  };
  print(await browser.navigateTab(tabRef, body));
};

CMD['browser-tab-evaluate'] = async () => {
  const [tabRef, ...expressionParts] = cmdArgs;
  if (!tabRef || expressionParts.length === 0) {
    console.error('Usage: rtx.js browser-tab-evaluate <tab-ref> <expression> [--user-gesture=true|false]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  const body = {
    expression: expressionParts.join(' '),
    ...(flags['user-gesture'] !== undefined ? { userGesture: flags['user-gesture'] !== 'false' } : {}),
  };
  print(await browser.evaluateTab(tabRef, body));
};

CMD['browser-tab-close'] = async () => {
  const [tabRef] = cmdArgs;
  if (!tabRef) {
    console.error('Usage: rtx.js browser-tab-close <tab-ref>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const browser = getDesktopBrowserModule(sdk);
  print(await browser.deleteTab(tabRef));
};

// -- acp-agents -------------------------------------------------------------
// Source: AcpAgentModule.listAgents({ includeModels? })
// Returns: AcpAgentInfo[] { id, label, handles[], installed, authReady, status }
CMD['acp-agents'] = async () => {
  const { sdk } = await getSDK();
  printTable(await sdk.acpAgent.listAgents({ includeModels: flags.models === 'true' }), ['id', 'label', 'status', 'authReady', 'installed']);
};

// -- acp-sessions -----------------------------------------------------------
// Source: AcpAgentModule.listSessions() → AcpSessionStatus[]
CMD['acp-sessions'] = async () => {
  const { sdk } = await getSDK();
  print(await sdk.acpAgent.listSessions());
};

// -- acp-session-create -----------------------------------------------------
// Source: AcpAgentModule.createSession(options) → AcpSession { session_key, agent_id, state, ... }
// Prints session_key so callers can pass --session=<key> on subsequent calls.
CMD['acp-session-create'] = async () => {
  const [agentId] = cmdArgs;
  if (!agentId) {
    console.error('Usage: rtx.js acp-session-create <agent-id> [--cwd=<path>] [--model=<m>] [--policy=approve-all|approve-reads|deny-all]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const opts = {
    agent_id: agentId,
    cwd: flags.cwd || process.cwd(),
    approvalPolicy: flags.policy || 'approve-all',
  };
  if (flags.model) opts.model = flags.model;
  const session = await sdk.acpAgent.createSession(opts);
  process.stderr.write('Session created.\n');
  print(session);
};

// -- acp-session-get --------------------------------------------------------
// Source: AcpAgentModule.getSession(sessionKey) → AcpSessionStatus
CMD['acp-session-get'] = async () => {
  const [sessionKey] = cmdArgs;
  if (!sessionKey) { console.error('Usage: rtx.js acp-session-get <session-key>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.acpAgent.getSession(sessionKey));
};

// -- acp-session-patch ------------------------------------------------------
// Source: AcpAgentModule.patchSession(sessionKey, patch) → void
// patch fields: model?, cwd?, timeoutSeconds?, runtimeMode?, approvalPolicy?
CMD['acp-session-patch'] = async () => {
  const [sessionKey] = cmdArgs;
  if (!sessionKey) {
    console.error('Usage: rtx.js acp-session-patch <session-key> [--cwd=<path>] [--model=<m>] [--policy=<p>] [--timeout=<s>]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const patch = {};
  if (flags.cwd)     patch.cwd            = flags.cwd;
  if (flags.model)   patch.model          = flags.model;
  if (flags.policy)  patch.approvalPolicy = flags.policy;
  if (flags.timeout) patch.timeoutSeconds = Number(flags.timeout);
  await sdk.acpAgent.patchSession(sessionKey, patch);
  console.log('Session patched.');
};

// -- acp-session-close ------------------------------------------------------
// Source: AcpAgentModule.closeSession(sessionKey, reason?) → void
CMD['acp-session-close'] = async () => {
  const [sessionKey, ...reasonParts] = cmdArgs;
  if (!sessionKey) { console.error('Usage: rtx.js acp-session-close <session-key> [<reason>]'); process.exit(1); }
  const { sdk } = await getSDK();
  await sdk.acpAgent.closeSession(sessionKey, reasonParts.join(' ') || undefined);
  console.log('Session closed.');
};

// -- acp-cancel -------------------------------------------------------------
// Source: AcpAgentModule.cancelTurn(sessionKey, reason?) → void
CMD['acp-cancel'] = async () => {
  const [sessionKey, ...reasonParts] = cmdArgs;
  if (!sessionKey) { console.error('Usage: rtx.js acp-cancel <session-key> [<reason>]'); process.exit(1); }
  const { sdk } = await getSDK();
  await sdk.acpAgent.cancelTurn(sessionKey, reasonParts.join(' ') || undefined);
  console.log('Turn cancelled.');
};

// -- acp-resolve ------------------------------------------------------------
// Source: AcpAgentModule.resolvePermission(sessionKey, { requestId, optionId, outcome? }) → void
// Must be called while streamChat SSE is still active for that session.
CMD['acp-resolve'] = async () => {
  const [sessionKey, requestId, optionId] = cmdArgs;
  if (!sessionKey || !requestId || !optionId) {
    console.error('Usage: rtx.js acp-resolve <session-key> <request-id> <option-id> [--outcome=approved]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  await sdk.acpAgent.resolvePermission(sessionKey, {
    requestId,
    optionId,
    outcome: flags.outcome || 'approved',
  });
  console.log('Permission resolved.');
};

// -- acp-send ---------------------------------------------------------------
// Source: AcpAgentModule.chat(sessionKey, message) → AcpChatResponse (sync, waits for full reply)
// Reuses existing session; never creates a new one.
CMD['acp-send'] = async () => {
  const [sessionKey, ...msgParts] = cmdArgs;
  const message = msgParts.join(' ');
  if (!sessionKey || !message) {
    console.error('Usage: rtx.js acp-send <session-key> <message>');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const res = await sdk.acpAgent.chat(sessionKey, message);
  console.log(res.text ?? JSON.stringify(res));
};

// -- acp-stream -------------------------------------------------------------
// Source: AcpAgentModule.streamChat(sessionKey, message) — SSE stream on existing session.
// Handles permission_request events automatically via resolvePermission().
// Reuses existing session; never creates a new one.
CMD['acp-stream'] = async () => {
  const [sessionKey, ...msgParts] = cmdArgs;
  const message = msgParts.join(' ');
  if (!sessionKey || !message) {
    console.error('Usage: rtx.js acp-stream <session-key> <message> [--thoughts] [--quiet]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  await acpStreamWithPermissions(sdk, sessionKey, message);
};

// ---------------------------------------------------------------------------
// ACP helpers
// ---------------------------------------------------------------------------

/**
 * Extract a stable string id from a permission option entry.
 * Options can be raw numbers, strings, or objects with numeric/string id fields.
 * IMPORTANT: must use != null (not ||) to handle id === 0 (falsy but valid).
 */
function optionId(opt, index) {
  if (opt == null)                    return String(index);
  if (typeof opt === 'number')        return String(opt);
  if (typeof opt === 'string')        return opt;
  if (opt.id       != null)           return String(opt.id);
  if (opt.optionId != null)           return String(opt.optionId);
  if (opt.value    != null)           return String(opt.value);
  return String(index);
}

/** Extract a human-readable label from a permission option entry. */
function optionLabel(opt, index) {
  if (opt == null)             return String(index);
  if (typeof opt === 'number') return String(opt);
  if (typeof opt === 'string') return opt;
  return opt.label || opt.name || opt.description || optionId(opt, index);
}

/**
 * Stream a chat turn on an existing session, auto-resolving permission_request
 * events via sdk.acpAgent.resolvePermission().
 *
 * Permission resolution strategy (--policy-override flag):
 *   approve-all  (default) — approve: label-match → last option (typically "Yes/Always")
 *   deny-all               — deny:    label-match → first option (typically "No/Cancel")
 *   prompt                 — pause and ask the user interactively via stdin
 *
 * Why last-option for approve-all fallback:
 *   Qwen/Claude-style dialogs are ordered [Deny=0, Approve-once=1, Approve-always=2].
 *   Picking options[0] = Deny. We want the last approve variant when no label matches.
 */
async function acpStreamWithPermissions(sdk, sessionKey, message) {
  const policyOverride = flags['policy-override'] || 'approve-all';

  for await (const event of sdk.acpAgent.streamChat(sessionKey, message)) {
    switch (event.type) {

      case 'text_delta': {
        if (event.data && event.data.type === 'thinking') {
          if (flags.thoughts) process.stderr.write('[thought] ' + String(event.data.text ?? '') + '\n');
        } else {
          process.stdout.write(String(event.data?.text ?? event.data ?? ''));
        }
        break;
      }

      case 'permission_request': {
        const req       = event.data || {};
        const requestId = req.requestId || req.id || req.request_id;
        const options   = Array.isArray(req.options) ? req.options : [];

        // Always show the full raw payload — critical for diagnosing option structure
        if (!flags.quiet) {
          process.stderr.write('\n[Permission Request] id=' + requestId + '\n');
          if (req.title)       process.stderr.write('  title:   ' + req.title + '\n');
          if (req.description) process.stderr.write('  details: ' + req.description + '\n');
          options.forEach((o, i) => {
            process.stderr.write('  [' + optionId(o, i) + '] ' + optionLabel(o, i) + '\n');
          });
          if (flags.debug) {
            process.stderr.write('  raw: ' + JSON.stringify(req) + '\n');
          }
        }

        let chosenId = null;

        if (policyOverride === 'prompt') {
          const readline = require('readline');
          const rl = readline.createInterface({ input: process.stdin, output: process.stderr });
          const answer = await new Promise(resolve => {
            rl.question('  Choose option id (Enter = last/approve): ', ans => { rl.close(); resolve(ans.trim()); });
          });
          // Use typed answer, or fall back to last option (approve-always)
          chosenId = answer || (options.length ? optionId(options[options.length - 1], options.length - 1) : null);

        } else if (policyOverride === 'deny-all') {
          // Label-match for deny keywords first, then fall back to first option (index 0 = No/Cancel)
          const idx = options.findIndex(o => /deny|cancel|no|reject/i.test(optionLabel(o, 0)));
          const pick = idx >= 0 ? options[idx] : options[0];
          const pickIdx = idx >= 0 ? idx : 0;
          if (pick != null) chosenId = optionId(pick, pickIdx);

        } else {
          // approve-all: label-match first, then LAST option (not first — first is typically Deny)
          const idx = options.findIndex(o => /approve|allow|yes|confirm|ok|always/i.test(optionLabel(o, 0)));
          if (idx >= 0) {
            chosenId = optionId(options[idx], idx);
          } else if (options.length > 0) {
            // Last option is safest approve fallback (e.g. "Yes, don't ask again" / "Approve always")
            const lastIdx = options.length - 1;
            chosenId = optionId(options[lastIdx], lastIdx);
          }
        }

        if (chosenId !== null && requestId) {
          if (!flags.quiet) process.stderr.write('  → resolving with option: ' + chosenId + '\n');
          await sdk.acpAgent.resolvePermission(sessionKey, {
            requestId,
            optionId: chosenId,
            outcome: policyOverride === 'deny-all' ? 'denied' : 'approved',
          });
        } else {
          if (!flags.quiet) process.stderr.write('  → no options to resolve\n');
        }
        break;
      }

      case 'tool_call': {
        if (!flags.quiet) {
          const tool = event.data?.tool || event.data?.name || JSON.stringify(event.data);
          process.stderr.write('\n[tool: ' + tool + ']\n');
        }
        break;
      }

      case 'status': {
        if (!flags.quiet && event.data?.message) {
          process.stderr.write('[status] ' + event.data.message + '\n');
        }
        break;
      }

      case 'error': {
        process.stderr.write('\n[Error] ' + (event.data?.message || JSON.stringify(event.data)) + '\n');
        break;
      }

      case 'done':
      case 'close':
        process.stdout.write('\n');
        break;

      default:
        if (flags.debug) process.stderr.write('[event:' + event.type + '] ' + JSON.stringify(event.data) + '\n');
        break;
    }
  }
}

/**
 * Find a reusable session for agentId+cwd, or create a fresh one.
 *
 * Resolution order:
 *   1. --session=<key>  → validate it exists and is not closed/stale, use it
 *   2. listSessions()   → find first session matching agent_id (and cwd if --cwd given)
 *                         whose state is not 'closed' or 'stale'
 *   3. createSession()  → spawn a new process
 *
 * Pass --new to always create a fresh session regardless.
 */
async function findOrCreateSession(sdk, agentId) {
  const cwd    = flags.cwd    || process.cwd();
  const policy = flags.policy || 'approve-all';

  // Force-new
  if (flags.new) {
    process.stderr.write('Creating new ACP session for "' + agentId + '"...\n');
    const s = await sdk.acpAgent.createSession({ agent_id: agentId, cwd, approvalPolicy: policy, ...(flags.model ? { model: flags.model } : {}) });
    process.stderr.write('Session: ' + s.session_key + '\n');
    return s.session_key;
  }

  // Explicit key
  if (flags.session) {
    try {
      const status = await sdk.acpAgent.getSession(flags.session);
      const state  = status?.state || status?.runtime_options?.state;
      if (state !== 'closed' && state !== 'stale') {
        process.stderr.write('Reusing session (--session): ' + flags.session + '\n');
        return flags.session;
      }
      process.stderr.write('Session ' + flags.session + ' is ' + state + ', will create new.\n');
    } catch (e) {
      process.stderr.write('Session lookup failed (' + (e.message || e) + '), will create new.\n');
    }
  }

  // Search existing sessions
  try {
    const sessions = await sdk.acpAgent.listSessions();
    if (Array.isArray(sessions)) {
      for (const s of sessions) {
        const key   = s.session_key || s.key;
        const sid   = s.agent_id   || s.agentId;
        const state = s.state      || s.runtime_options?.state;
        const sCwd  = s.cwd        || s.runtime_options?.cwd;
        if (state === 'closed' || state === 'stale') continue;
        if (sid && sid !== agentId) continue;
        if (flags.cwd && sCwd && sCwd !== cwd) continue;
        if (key) {
          process.stderr.write('Reusing existing session: ' + key + (sid ? ' (' + sid + ')' : '') + '\n');
          return key;
        }
      }
    }
  } catch (_) { /* listSessions not supported or empty — fall through */ }

  // Create new
  process.stderr.write('Creating new ACP session for "' + agentId + '"...\n');
  const session = await sdk.acpAgent.createSession({
    agent_id: agentId,
    cwd,
    approvalPolicy: policy,
    ...(flags.model ? { model: flags.model } : {}),
  });
  process.stderr.write('Session: ' + session.session_key + '\n');
  return session.session_key;
}

// -- acp-chat ---------------------------------------------------------------
// Smart version: reuses existing sessions, handles permission_request via resolvePermission().
//
// Flags:
//   --session=<key>           Reuse this specific session key
//   --new                     Always create a fresh session
//   --cwd=<path>              Working directory (used for new session + matching)
//   --model=<m>               Model override
//   --policy=approve-all      approvalPolicy for new sessions
//   --policy-override=<p>     Runtime permission decision: approve-all|deny-all|prompt
//   --close                   Close the session after this turn
//   --thoughts                Print reasoning/thinking tokens to stderr
//   --quiet                   Suppress tool/status/permission stderr output
//   --debug                   Print all unhandled SSE event types
CMD['acp-chat'] = async () => {
  const [agentId, ...msgParts] = cmdArgs;
  const message = msgParts.join(' ');
  if (!agentId || !message) {
    console.error('Usage: rtx.js acp-chat <agent-id> <message>\n' +
      '  [--session=<key>] [--new] [--cwd=<path>] [--model=<m>]\n' +
      '  [--policy=approve-all] [--policy-override=approve-all|deny-all|prompt]\n' +
      '  [--close] [--thoughts] [--quiet] [--debug]');
    process.exit(1);
  }
  const { sdk } = await getSDK();
  const sessionKey = await findOrCreateSession(sdk, agentId);

  try {
    await acpStreamWithPermissions(sdk, sessionKey, message);
  } finally {
    if (flags.close) {
      await sdk.acpAgent.closeSession(sessionKey, 'chat complete').catch(() => {});
      process.stderr.write('Session closed.\n');
    } else {
      process.stderr.write('Session key (reuse with --session=' + sessionKey + ')\n');
    }
  }
};

// -- tts-providers / stt-providers ------------------------------------------
CMD['tts-providers'] = async () => { const { sdk } = await getSDK(); printTable(await sdk.tts.listProviders(), ['id', 'name', 'type', 'configured', 'supportsStreaming']); };
CMD['stt-providers'] = async () => { const { sdk } = await getSDK(); print(await sdk.stt.listProviders()); };

// -- vectors ----------------------------------------------------------------
// Source: LLMModule.vectors (VectorStore sub-module)
CMD['vectors-workspaces'] = async () => { const { sdk } = await getSDK(); print(await sdk.llm.vectors.listWorkspaces()); };
// llm.search() embeds query then calls vectors.query() — high-level helper
CMD['vectors-query'] = async () => {
  const query = cmdArgs.join(' ');
  if (!query) { console.error('Usage: rtx.js vectors-query <query> [--workspace-id=<id>] [--top=5]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.llm.search(query, { topK: flags.top ? Number(flags.top) : 5, workspaceId: flags['workspace-id'] }));
};
// vectors.upsert: VectorRecord[] = { id, vector: number[], metadata? }
CMD['vectors-upsert'] = async () => {
  const [jsonStr] = cmdArgs;
  if (!jsonStr) { console.error('Usage: rtx.js vectors-upsert <json-VectorRecord[]> [--workspace-id=<id>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.llm.vectors.upsert(JSON.parse(jsonStr), { workspaceId: flags['workspace-id'] }));
};
// vectors.delete requires { deleteAll: true } — partial delete by ID not supported
CMD['vectors-delete'] = async () => {
  if (!flags['workspace-id'] && !flags.all) { console.error('Usage: rtx.js vectors-delete --workspace-id=<id>  OR  --all'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.llm.vectors.delete({ deleteAll: true, workspaceId: flags['workspace-id'] }));
};

// -- contract ---------------------------------------------------------------
CMD['contract-info']         = async () => { const { sdk } = await getSDK(); print(await sdk.contract.getLocalAppV1()); };
CMD['contract-capabilities'] = async () => { const { sdk } = await getSDK(); print(await sdk.contract.listCapabilities()); };
CMD['contract-search']       = async () => {
  const query = cmdArgs.join(' ');
  if (!query) { console.error('Usage: rtx.js contract-search <query>'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.contract.searchCapabilities(query));
};
CMD['contract-invoke'] = async () => {
  const [capId, ...rest] = cmdArgs;
  if (!capId) { console.error('Usage: rtx.js contract-invoke <capability-id> [<args-json>]'); process.exit(1); }
  const { sdk } = await getSDK();
  print(await sdk.contract.invoke({ capability_id: capId, args: rest[0] ? JSON.parse(rest[0]) : {}, auto_run: true, agent_name: flags.agent, workspace_slug: flags.workspace, prompt: flags.prompt }));
};

// -- database / auth --------------------------------------------------------
CMD['db-config']   = async () => { const { sdk } = await getSDK(); print(await sdk.database.getConfig()); };
CMD['auth-token']  = async () => { const { sdk } = await getSDK(); print(await sdk.auth.getAccessToken()); };

// -- help -------------------------------------------------------------------
CMD.help = async () => {
  console.log(`
RealTimeX SDK CLI (source-verified) — rtx.js
============================================

Usage: node rtx.js <command> [args...] [--flags]

Global flags:
  --api-key=<key>       Override API key (skips .env lookup)
  --env-dir=<path>      Directory containing .env (default: cwd)
  --url=<url>           RealTimeX server URL (default: http://localhost:3001)

Connection:
  ping / info

sdk.api.*:
  agents / workspaces / threads <slug> / task <uuid>
  context

sdk.activities.*:
  activities [--status --limit --offset]
  activity-get <id>
  activity-create <json>
  activity-update <id> <json>
  activity-delete <id>

sdk.task.*  (positional args — NOT { task_uuid }):
  task-start <uuid> [--machine=<id>]
  task-complete <uuid> [<result-json>] [--machine=<id>]
  task-fail <uuid> <error-message>
  task-progress <uuid> [<progress-json>]
  task-cancel <uuid> [<reason>]

Trigger  (raw fetch — SDK method sends wrong event type):
  trigger-agent <agent-name> <workspace-slug> <prompt>
    [--thread=<slug>] [--data=<json>]

Webhook:
  webhook-ping

sdk.llm.*:
  llm-providers / embed-providers
  llm-chat <message> [--stream] [--model] [--provider]
  llm-embed <text> [--model] [--vectors]

sdk.llm.vectors.*:
  vectors-workspaces
  vectors-query <text> [--workspace-id] [--top=5]
  vectors-upsert <json-VectorRecord[]> [--workspace-id]
  vectors-delete --workspace-id=<id> | --all

sdk.mcp.*:
  mcp-servers [--provider=local|remote|all]
  mcp-tools <server> [--provider]
  mcp-exec <server> <tool> [<args-json>] [--provider]

sdk.credentials.*:
  credentials
    List available credentials (names and types, no values).

sdk.desktopRuntimeSessions.* — Desktop terminal sessions:
  terminal-open-launcher
    [--workspace=<slug>] [--thread=<slug>] [--presentation=panel|tab]
    Open the terminal launcher UI in the Electron app.

  terminal-launch-shell
    [--workspace=<slug>] [--thread=<slug>] [--presentation=panel|tab]
    [--command="pwd"] [--command-mode=direct|prefill|shell]
    Launch a visible shell terminal.
    Default: when --command is provided, it runs in direct mode unless --command-mode is explicitly set.

  terminal-launch-cli-agent <agent-name> [<provider-id>] [<message>]
    [--workspace=<slug>] [--thread=<slug>] [--presentation=panel|tab] [--model=<id>]
    Launch a visible CLI agent terminal.
    Example: terminal-launch-cli-agent claude claude-cli "what is current working dir"

  terminal-sessions
    List desktop terminal sessions.

  terminal-session-get <session-id>
    Fetch one desktop terminal session by runtime session id.

  terminal-write <session-id> <message> [--raw]
    Send another message or raw PTY input to an existing terminal session.

  terminal-permission <session-id> <approved|denied> [<action-id>] [--option-id=<id>] [--reason=<text>]
    Resolve a pending terminal approval request.

  terminal-close <session-id>
    Close a desktop terminal session.

  Compatibility:
    The SDK also exposes this module as sdk.v1.desktopRuntimeSessions.

sdk.desktopBrowser.* — RealTimeX Browser sessions and tabs:
  browser-sessions
    List named RealTimeX Browser sessions.

  browser-session-create <session-name> [--port=<n>]
    Create a named browser session.

  browser-session-get <session-name>
    Fetch one named browser session.

  browser-session-delete <session-name>
    Delete a named browser session.

  browser-tab-create <url> [--session=<name>] [--focus=true|false] [--focus-window=true|false]
    Create a managed browser tab.

  browser-tab-get <tab-ref>
    Fetch one browser tab snapshot by tab ref.

  browser-tab-focus <tab-ref> [--focus-window=true|false]
    Focus a managed browser tab.

  browser-tab-navigate <tab-ref> <url> [--focus=true|false] [--focus-window=true|false]
    Navigate a managed browser tab.

  browser-tab-evaluate <tab-ref> <expression> [--user-gesture=true|false]
    Evaluate JavaScript in a managed browser tab.

  browser-tab-close <tab-ref>
    Close a managed browser tab.

  Workflow note:
    Each session has seperated browser profile, use session's remoteDebugPort with the agent-browser skill
    over CDP for page interaction and automation.

  Compatibility:
    The SDK also exposes this module as sdk.v1.desktopBrowser.

sdk.acpAgent.* — Session Management:
  acp-agents [--models=true]
    List available ACP CLI agents.

  acp-sessions
    List all active sessions owned by this app.

  acp-session-create <agent-id>
    [--cwd=<path>] [--model=<m>] [--policy=approve-all|approve-reads|deny-all]
    Spawn a new agent process. Prints session_key for reuse.

  acp-session-get <session-key>
    Get session status and runtime options.

  acp-session-patch <session-key>
    [--cwd=<path>] [--model=<m>] [--policy=<p>] [--timeout=<s>]
    Update runtime options (applied on next turn).

  acp-session-close <session-key> [<reason>]
    Stop the agent process and close the session.

  acp-cancel <session-key> [<reason>]
    Cancel the currently active turn on a session.

  acp-resolve <session-key> <request-id> <option-id> [--outcome=approved]
    Manually resolve a pending permission request (while stream is active).

  acp-send <session-key> <message>
    Synchronous chat on an existing session (waits for full reply).

  acp-stream <session-key> <message>
    [--policy-override=approve-all|deny-all|prompt] [--thoughts] [--quiet] [--debug]
    Streaming chat on an existing session. Auto-resolves permission_request events.

  acp-chat <agent-id> <message>
    [--session=<key>]  Reuse a specific session key
    [--new]            Force-create a new session
    [--cwd=<path>]     Working directory (for new session and session matching)
    [--model=<m>]      Model override
    [--policy=approve-all]  approvalPolicy for newly created sessions
    [--policy-override=approve-all|deny-all|prompt]  Runtime permission handling
    [--close]          Close session after this turn
    [--thoughts]       Print reasoning tokens to stderr
    [--quiet]          Suppress tool/status/permission stderr output
    [--debug]          Print all unhandled SSE events

    Smart session reuse: checks --session flag → searches listSessions() for a
    compatible active session → creates new only if none found.
    Handles permission_request events inline via resolvePermission().

sdk.tts.* / sdk.stt.*:
  tts-providers / stt-providers

sdk.contract.*:
  contract-info / contract-capabilities
  contract-search <query>
  contract-invoke <capability-id> [<args-json>] [--agent] [--workspace] [--prompt]

sdk.database.* / sdk.auth.*:
  db-config / auth-token

  help
`);
};

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------
(async () => {
  const handler = CMD[command];
  if (!handler) {
    console.error('Unknown command: ' + (command || '(none)') + '\nRun: node rtx.js help');
    process.exit(1);
  }
  try {
    await handler();
    process.exit(0);
  } catch (err) {
    console.error('Error:', err.message || err);
    if (flags.debug) console.error(err);
    process.exit(1);
  }
})();
