// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: ACP Auth

import { DeveloperApiClient } from '../client';

export class V1AcpAuthModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see GET /v1/acp/auth/profiles */
    async listProfiles(): Promise<unknown> {
        return this.client.request('GET', `/v1/acp/auth/profiles`);
    }

    /** @see POST /v1/acp/auth/profiles */
    async createProfile(): Promise<unknown> {
        return this.client.request('POST', `/v1/acp/auth/profiles`);
    }

    /** @see GET /v1/acp/auth/status */
    async getStatus(): Promise<unknown> {
        return this.client.request('GET', `/v1/acp/auth/status`);
    }

    /** @see DELETE /v1/acp/auth/profiles/{id} */
    async deleteProfile(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/acp/auth/profiles/${id}`);
    }
}
