// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: ACP Commands

import { DeveloperApiClient } from '../client';

export class V1AcpCommandsModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see POST /v1/acp/command */
    async createCommand(): Promise<unknown> {
        return this.client.request('POST', `/v1/acp/command`);
    }

    /** @see POST /v1/acp/command/permission-decision */
    async permissionDecision(): Promise<unknown> {
        return this.client.request('POST', `/v1/acp/command/permission-decision`);
    }
}
