// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 146edc2864715e5d
// Tag: Admin

import { DeveloperApiClient } from '../client';

export class V1AdminModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Check to see if the instance is in multi-user-mode first. Methods are disabled until multi user mode is enabled via the UI.
     * @see GET /v1/admin/is-multi-user-mode
     */
    async getIsMultiUserMode(): Promise<unknown> {
        return this.client.request('GET', `/v1/admin/is-multi-user-mode`);
    }

    /**
     * Check to see if the instance is in multi-user-mode first. Methods are disabled until multi user mode is enabled via the UI.
     * @see GET /v1/admin/users
     */
    async listUsers(): Promise<unknown> {
        return this.client.request('GET', `/v1/admin/users`);
    }

    /**
     * Create a new user with username and password. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/users/new
     */
    async createUser(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/users/new`, body);
    }

    /**
     * Update existing user settings. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/users/{id}
     */
    async updateUser(id: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/users/${id}`, body);
    }

    /**
     * Delete existing user by id. Methods are disabled until multi user mode is enabled via the UI.
     * @see DELETE /v1/admin/users/{id}
     */
    async deleteUser(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/admin/users/${id}`);
    }

    /**
     * List all existing invitations to instance regardless of status. Methods are disabled until multi user mode is enabled via the UI.
     * @see GET /v1/admin/invites
     */
    async listInvites(): Promise<unknown> {
        return this.client.request('GET', `/v1/admin/invites`);
    }

    /**
     * Create a new invite code for someone to use to register with instance. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/invite/new
     */
    async createInvite(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/invite/new`, body);
    }

    /**
     * Deactivates (soft-delete) invite by id. Methods are disabled until multi user mode is enabled via the UI.
     * @see DELETE /v1/admin/invite/{id}
     */
    async deleteInvite(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/admin/invite/${id}`);
    }

    /**
     * Retrieve a list of users with permissions to access the specified workspace.
     * @see GET /v1/admin/workspaces/{workspaceId}/users
     */
    async listWorkspaceUsers(workspaceId: string): Promise<unknown> {
        return this.client.request('GET', `/v1/admin/workspaces/${workspaceId}/users`);
    }

    /**
     * Overwrite workspace permissions to only be accessible by the given user ids and admins. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/workspaces/{workspaceId}/update-users
     */
    async updateUsers(workspaceId: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/workspaces/${workspaceId}/update-users`, body);
    }

    /**
     * Set workspace permissions to be accessible by the given user ids and admins. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/workspaces/{workspaceSlug}/manage-users
     */
    async workspacesManageUsers(workspaceSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/workspaces/${workspaceSlug}/manage-users`, body);
    }

    /**
     * All chats in the system ordered by most recent. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/workspace-chats
     */
    async workspaceChats(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/workspace-chats`, body);
    }

    /**
     * Update multi-user preferences for instance. Methods are disabled until multi user mode is enabled via the UI.
     * @see POST /v1/admin/preferences
     */
    async createPreference(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/admin/preferences`, body);
    }
}
