// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: e71106ae34cd13c9
// Tag: Authentication

import { DeveloperApiClient } from '../client';

export class V1AuthModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Verify the attached Authentication header contains a valid API token.
     * @see GET /v1/auth
     */
    async getAuth(): Promise<unknown> {
        return this.client.request('GET', `/v1/auth`);
    }
}
