// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 90a37390a78f04cb
// Tag: Authentication

import { DeveloperApiClient } from '../client';

export class V1AuthModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Verify the attached Authentication header contains a valid API token.
     * @see GET /v1/auth
     */
    async getAuth(): Promise<unknown> {
        return this.client.request('GET', `/v1/auth`);
    }

    /**
     * Relay external browser auth callbacks back to the local Electron renderer. Localhost only; keyed by OAuth state.
     * @see POST /v1/auth/external-callback
     */
    async externalCallback(): Promise<unknown> {
        return this.client.request('POST', `/v1/auth/external-callback`);
    }

    /**
     * Poll for a relayed external browser auth callback by OAuth state. Localhost only.
     * @see GET /v1/auth/external-callback/{state}
     */
    async getExternalCallback(state: string): Promise<unknown> {
        return this.client.request('GET', `/v1/auth/external-callback/${state}`);
    }
}
