// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 6e1eed2d292acbcc
// Tag: Chat

import { DeveloperApiClient } from '../client';

export class V1ChatModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Stream a chat response for a workspace default thread.
     * @see POST /v1/workspace/{slug}/stream-chat
     */
    // @streaming-stub — implement SSE parsing in overrides/v1ChatStreaming.ts
    async streamWorkspaceChat(slug: string, body?: Record<string, unknown>): Promise<Response> {
        return this.client.requestRaw('POST', `/v1/workspace/${slug}/stream-chat`, body);
    }

    /**
     * Stream a chat response for a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/stream-chat
     */
    // @streaming-stub — implement SSE parsing in overrides/v1ChatStreaming.ts
    async streamThreadChat(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<Response> {
        return this.client.requestRaw('POST', `/v1/workspace/${slug}/thread/${threadSlug}/stream-chat`, body);
    }
}
