// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 146edc2864715e5d
// Tag: Channels

import { DeveloperApiClient } from '../client';

export class V1ChannelsModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * List configured channel plugins without exposing encrypted plugin configuration.
     * @see GET /v1/channels/plugins
     */
    async listPlugins(): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins`);
    }

    /**
     * Create a channel plugin. The request may include provider credentials in config, but credentials are never returned.
     * @see POST /v1/channels/plugins
     */
    async createPlugin(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins`, body);
    }

    /**
     * Get editable non-secret channel plugin configuration.
     * @see GET /v1/channels/plugins/{id}/config
     */
    async getConfig(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/config`);
    }

    /**
     * Update a channel plugin. Config values are encrypted before storage.
     * @see POST /v1/channels/plugins/{id}/update
     */
    async updatePlugin(id: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/update`, body);
    }

    /**
     * Delete a channel plugin and stop any running plugin instance.
     * @see DELETE /v1/channels/plugins/{id}
     */
    async deletePlugin(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/channels/plugins/${id}`);
    }

    /**
     * Enable and start a channel plugin.
     * @see POST /v1/channels/plugins/{id}/start
     */
    async pluginsStart(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/start`);
    }

    /**
     * Disable and stop a channel plugin.
     * @see POST /v1/channels/plugins/{id}/stop
     */
    async pluginsStop(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/stop`);
    }

    /**
     * Test channel provider credentials without saving a plugin.
     * @see POST /v1/channels/plugins/test
     */
    async pluginsTest(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/test`, body);
    }

    /**
     * Get runtime status for all running channel plugins.
     * @see GET /v1/channels/status
     */
    async getStatus(): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/status`);
    }

    /**
     * Start a QR login flow for Zalo personal or WhatsApp plugins.
     * @see POST /v1/channels/plugins/{id}/qr-login/start
     */
    async pluginsQrLoginStart(id: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/qr-login/start`, body);
    }

    /**
     * Poll QR login status for Zalo personal or WhatsApp plugins.
     * @see GET /v1/channels/plugins/{id}/qr-login/state
     */
    async getState(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/qr-login/state`);
    }

    /**
     * Cancel a QR login flow for Zalo personal or WhatsApp plugins.
     * @see POST /v1/channels/plugins/{id}/qr-login/cancel
     */
    async pluginsQrLoginCancel(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/qr-login/cancel`);
    }

    /**
     * Log out a QR-authenticated Zalo personal or WhatsApp plugin and clear stored credentials.
     * @see POST /v1/channels/plugins/{id}/logout
     */
    async pluginsLogout(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/logout`);
    }

    /**
     * Update safe channel policies for Zalo personal or WhatsApp plugins without overwriting credentials.
     * @see POST /v1/channels/plugins/{id}/policies
     */
    async pluginsPolicies(id: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/policies`, body);
    }

    /**
     * Search a Zalo personal friends directory.
     * @see GET /v1/channels/plugins/{id}/directory/friends
     */
    async listDirectoryFriends(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/directory/friends`);
    }

    /**
     * Search a Zalo personal groups directory.
     * @see GET /v1/channels/plugins/{id}/directory/groups
     */
    async listDirectoryGroups(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/directory/groups`);
    }

    /**
     * List pending pairing codes for a channel plugin.
     * @see GET /v1/channels/plugins/{id}/pairing-codes
     */
    async listPluginPairingCodes(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/pairing-codes`);
    }

    /**
     * Generate a pairing code for a channel plugin.
     * @see POST /v1/channels/plugins/{id}/pairing-codes
     */
    async pluginsPairingCodes(id: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/pairing-codes`, body);
    }

    /**
     * Approve a channel pairing code.
     * @see POST /v1/channels/pairing-codes/{id}/approve
     */
    async pairingCodesApprove(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/pairing-codes/${id}/approve`);
    }

    /**
     * Reject a channel pairing code.
     * @see POST /v1/channels/pairing-codes/{id}/reject
     */
    async pairingCodesReject(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/pairing-codes/${id}/reject`);
    }

    /**
     * List channel users for a plugin.
     * @see GET /v1/channels/plugins/{id}/users
     */
    async listPluginUsers(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/channels/plugins/${id}/users`);
    }

    /**
     * Set authorization for a channel user.
     * @see POST /v1/channels/plugins/{id}/users/{userId}/authorization
     */
    async pluginsUsersAuthorization(id: string, userId: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/channels/plugins/${id}/users/${userId}/authorization`, body);
    }

    /**
     * Remove a channel user from a plugin.
     * @see DELETE /v1/channels/plugins/{id}/users/{userId}
     */
    async deleteUser(id: string, userId: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/channels/plugins/${id}/users/${userId}`);
    }
}
