// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: Credentials

import { DeveloperApiClient } from '../client';

export class V1CredentialsModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see POST /v1/credentials */
    async createCredential(): Promise<unknown> {
        return this.client.request('POST', `/v1/credentials`);
    }

    /** @see GET /v1/credentials */
    async listCredentials(): Promise<unknown> {
        return this.client.request('GET', `/v1/credentials`);
    }

    /** @see GET /v1/credentials/{id} */
    async getCredential(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/credentials/${id}`);
    }

    /** @see PUT /v1/credentials/{id} */
    async replaceCredential(id: string): Promise<unknown> {
        return this.client.request('PUT', `/v1/credentials/${id}`);
    }

    /** @see DELETE /v1/credentials/{id} */
    async deleteCredential(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/credentials/${id}`);
    }

    /** @see POST /v1/credentials/{id}/restore */
    async restore(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/credentials/${id}/restore`);
    }
}
