// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: Custom Themes

import { DeveloperApiClient } from '../client';

export class V1CustomThemesModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see GET /v1/custom-themes */
    async listCustomThemes(): Promise<unknown> {
        return this.client.request('GET', `/v1/custom-themes`);
    }

    /** @see GET /v1/custom-themes/{id} */
    async getCustomTheme(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/custom-themes/${id}`);
    }

    /** @see POST /v1/custom-themes/{id} */
    async updateCustomTheme(id: string): Promise<unknown> {
        return this.client.request('POST', `/v1/custom-themes/${id}`);
    }

    /** @see DELETE /v1/custom-themes/{id} */
    async deleteCustomTheme(id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/custom-themes/${id}`);
    }

    /** @see POST /v1/custom-themes/new */
    async createCustomTheme(): Promise<unknown> {
        return this.client.request('POST', `/v1/custom-themes/new`);
    }
}
