// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 43c4c5a2e59c85e9
// Tag: SDK - Desktop Runtime Sessions

import { DeveloperApiClient } from '../client';

export class V1DesktopRuntimeSessionsModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Open the shared terminal launcher in the Electron desktop app.
     * @see POST /sdk/desktop/runtime-sessions/open-launcher
     */
    async openLauncher(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/runtime-sessions/open-launcher`, body);
    }

    /**
     * Launch a local PTY-backed shell terminal in the Electron desktop app.
     * @see POST /sdk/desktop/runtime-sessions/launch-terminal-shell
     */
    async launchTerminalShell(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/runtime-sessions/launch-terminal-shell`, body);
    }

    /**
     * Launch a local PTY-backed CLI agent terminal in the Electron desktop app.
     * @see POST /sdk/desktop/runtime-sessions/launch-terminal-cli-agent
     */
    async launchTerminalCliAgent(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/runtime-sessions/launch-terminal-cli-agent`, body);
    }

    /**
     * List desktop PTY-backed runtime sessions currently known to the Electron app.
     * @see GET /sdk/desktop/runtime-sessions
     */
    async listRuntimeSessions(): Promise<unknown> {
        return this.client.request('GET', `/sdk/desktop/runtime-sessions`);
    }

    /**
     * Fetch one desktop PTY-backed runtime session by runtime session ID or PTY session ID.
     * @see GET /sdk/desktop/runtime-sessions/{sessionId}
     */
    async getRuntimeSession(sessionId: string): Promise<unknown> {
        return this.client.request('GET', `/sdk/desktop/runtime-sessions/${sessionId}`);
    }

    /**
     * Close an existing desktop runtime session.
     * @see DELETE /sdk/desktop/runtime-sessions/{sessionId}
     */
    async deleteRuntimeSession(sessionId: string): Promise<unknown> {
        return this.client.request('DELETE', `/sdk/desktop/runtime-sessions/${sessionId}`);
    }

    /**
     * Write input to an existing desktop runtime session. Use `message` to submit a CLI turn or `input` for raw PTY data.
     * @see POST /sdk/desktop/runtime-sessions/{sessionId}/write
     */
    async write(sessionId: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/runtime-sessions/${sessionId}/write`, body);
    }

    /**
     * Approve or deny a pending desktop runtime session action.
     * @see POST /sdk/desktop/runtime-sessions/{sessionId}/permission
     */
    async permission(sessionId: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/runtime-sessions/${sessionId}/permission`, body);
    }
}
