// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 4bf39d5450c53d1c
// Tag: SDK - Desktop Browser

import { DeveloperApiClient } from '../client';

export class V1DesktopBrowserModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * List RealTimeX Browser sessions available in the Electron desktop app.
     * @see GET /sdk/desktop/browser/sessions
     */
    async listSessions(): Promise<unknown> {
        return this.client.request('GET', `/sdk/desktop/browser/sessions`);
    }

    /**
     * Create a named RealTimeX Browser session in the Electron desktop app.
     * @see POST /sdk/desktop/browser/sessions
     */
    async createSession(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/browser/sessions`, body);
    }

    /**
     * Get a specific RealTimeX Browser session by session name.
     * @see GET /sdk/desktop/browser/sessions/{sessionName}
     */
    async getSession(sessionName: string): Promise<unknown> {
        return this.client.request('GET', `/sdk/desktop/browser/sessions/${sessionName}`);
    }

    /**
     * Delete a named RealTimeX Browser session from the Electron desktop app.
     * @see DELETE /sdk/desktop/browser/sessions/{sessionName}
     */
    async deleteSession(sessionName: string): Promise<unknown> {
        return this.client.request('DELETE', `/sdk/desktop/browser/sessions/${sessionName}`);
    }

    /**
     * Create a RealTimeX Browser tab, optionally launching the browser session if needed.
     * @see POST /sdk/desktop/browser/tabs
     */
    async createTab(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/browser/tabs`, body);
    }

    /**
     * Get a RealTimeX Browser tab snapshot by tab reference.
     * @see GET /sdk/desktop/browser/tabs/{tabRef}
     */
    async getTab(tabRef: string): Promise<unknown> {
        return this.client.request('GET', `/sdk/desktop/browser/tabs/${tabRef}`);
    }

    /**
     * Close an existing RealTimeX Browser tab.
     * @see DELETE /sdk/desktop/browser/tabs/{tabRef}
     */
    async deleteTab(tabRef: string): Promise<unknown> {
        return this.client.request('DELETE', `/sdk/desktop/browser/tabs/${tabRef}`);
    }

    /**
     * Evaluate JavaScript in a specific RealTimeX Browser tab.
     * @see POST /sdk/desktop/browser/tabs/{tabRef}/evaluate
     */
    async evaluateTab(tabRef: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/browser/tabs/${tabRef}/evaluate`, body);
    }

    /**
     * Focus an existing RealTimeX Browser tab.
     * @see POST /sdk/desktop/browser/tabs/{tabRef}/focus
     */
    async focusTab(tabRef: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/browser/tabs/${tabRef}/focus`, body);
    }

    /**
     * Navigate an existing RealTimeX Browser tab to a new URL.
     * @see POST /sdk/desktop/browser/tabs/{tabRef}/navigate
     */
    async navigateTab(tabRef: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/sdk/desktop/browser/tabs/${tabRef}/navigate`, body);
    }
}
