// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: Desktop Embed

import { DeveloperApiClient } from '../client';

export class V1DesktopEmbedModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see GET /v1/desktop-public-embed/status */
    async getStatus(): Promise<unknown> {
        return this.client.request('GET', `/v1/desktop-public-embed/status`);
    }

    /** @see POST /v1/desktop-public-embed/exposures */
    async createExposure(): Promise<unknown> {
        return this.client.request('POST', `/v1/desktop-public-embed/exposures`);
    }

    /** @see POST /v1/desktop-public-embed/exposures/{exposureId}/heartbeat */
    async exposuresHeartbeat(exposureId: string): Promise<unknown> {
        return this.client.request('POST', `/v1/desktop-public-embed/exposures/${exposureId}/heartbeat`);
    }

    /** @see GET /v1/desktop-public-embed/exposures/{exposureId} */
    async getExposure(exposureId: string): Promise<unknown> {
        return this.client.request('GET', `/v1/desktop-public-embed/exposures/${exposureId}`);
    }

    /** @see DELETE /v1/desktop-public-embed/exposures/{exposureId} */
    async deleteExposure(exposureId: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/desktop-public-embed/exposures/${exposureId}`);
    }
}
