// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 43c4c5a2e59c85e9
// Tag: Documents

import { DeveloperApiClient } from '../client';

export class V1DocumentModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Upload a new file to RealTimeX to be parsed and prepared for embedding.
     * @see POST /v1/document/upload
     */
    // @upload-stub — multipart upload; wire form manually or use helper
    async upload(form: FormData): Promise<unknown> {
        return this.client.requestMultipart('POST', `/v1/document/upload`, form);
    }

    /**
     * Upload a new file to a specific folder in RealTimeX to be parsed and prepared for embedding. If the folder does not exist, it will be created.
     * @see POST /v1/document/upload/{folderName}
     */
    // @upload-stub — multipart upload; wire form manually or use helper
    async uploadFolder(folderName: string, form: FormData): Promise<unknown> {
        return this.client.requestMultipart('POST', `/v1/document/upload/${folderName}`, form);
    }

    /**
     * Upload a valid URL for RealTimeX to scrape and prepare for embedding. Optionally, specify a comma-separated list of workspace slugs to embed the document into post-upload.
     * @see POST /v1/document/upload-link
     */
    async uploadLink(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/document/upload-link`, body);
    }

    /**
     * Upload a file by specifying its raw text content and metadata values without having to upload a file.
     * @see POST /v1/document/raw-text
     */
    async rawText(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/document/raw-text`, body);
    }

    /**
     * List of all locally-stored documents in instance
     * @see GET /v1/documents
     */
    async listDocuments(): Promise<unknown> {
        return this.client.request('GET', `/v1/documents`);
    }

    /**
     * Get all documents stored in a specific folder.
     * @see GET /v1/documents/folder/{folderName}
     */
    async getFolder(folderName: string): Promise<unknown> {
        return this.client.request('GET', `/v1/documents/folder/${folderName}`);
    }

    /**
     * Check available filetypes and MIMEs that can be uploaded.
     * @see GET /v1/document/accepted-file-types
     */
    async listAcceptedFileTypes(): Promise<unknown> {
        return this.client.request('GET', `/v1/document/accepted-file-types`);
    }

    /**
     * Get the known available metadata schema for when doing a raw-text upload and the acceptable type of value for each key.
     * @see GET /v1/document/metadata-schema
     */
    async getMetadataSchema(): Promise<unknown> {
        return this.client.request('GET', `/v1/document/metadata-schema`);
    }

    /**
     * Get a single document by its unique RealTimeX document name
     * @see GET /v1/document/{docName}
     */
    async getDocument(docName: string): Promise<unknown> {
        return this.client.request('GET', `/v1/document/${docName}`);
    }

    /**
     * Create a new folder inside the documents storage directory.
     * @see POST /v1/document/create-folder
     */
    async createFolder(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/document/create-folder`, body);
    }

    /**
     * Remove a folder and all its contents from the documents storage directory.
     * @see DELETE /v1/document/remove-folder
     */
    async deleteRemoveFolder(): Promise<unknown> {
        return this.client.request('DELETE', `/v1/document/remove-folder`);
    }

    /**
     * Move files within the documents storage directory.
     * @see POST /v1/document/move-files
     */
    async moveFiles(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/document/move-files`, body);
    }
}
