// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 1018f7f1fd928ad4
// Tag: Embed

import { DeveloperApiClient } from '../client';

export class V1EmbedModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * List all active embeds
     * @see GET /v1/embed
     */
    async getEmbed(): Promise<unknown> {
        return this.client.request('GET', `/v1/embed`);
    }

    /**
     * Get all chats for a specific embed
     * @see GET /v1/embed/{embedUuid}/chats
     */
    async listChats(embedUuid: string): Promise<unknown> {
        return this.client.request('GET', `/v1/embed/${embedUuid}/chats`);
    }

    /**
     * Get chats for a specific embed and session
     * @see GET /v1/embed/{embedUuid}/chats/{sessionUuid}
     */
    async getChat(embedUuid: string, sessionUuid: string): Promise<unknown> {
        return this.client.request('GET', `/v1/embed/${embedUuid}/chats/${sessionUuid}`);
    }

    /**
     * Create a new embed configuration
     * @see POST /v1/embed/new
     */
    async createEmbed(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/embed/new`, body);
    }

    /**
     * Update an existing embed configuration
     * @see POST /v1/embed/{embedUuid}
     */
    async updateEmbed(embedUuid: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/embed/${embedUuid}`, body);
    }

    /**
     * Delete an existing embed configuration
     * @see DELETE /v1/embed/{embedUuid}
     */
    async deleteEmbed(embedUuid: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/embed/${embedUuid}`);
    }
}
