// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: OpenAI Compatible Endpoints

import { DeveloperApiClient } from '../client';

export class V1OpenAIModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Get all available "models" which are workspaces you can use for chatting.
     * @see GET /v1/openai/models
     */
    async listModels(): Promise<unknown> {
        return this.client.request('GET', `/v1/openai/models`);
    }

    /**
     * Execute a chat with a workspace with OpenAI compatibility. Supports streaming as well. Model must be a workspace slug from /models.
     * @see POST /v1/openai/chat/completions
     */
    async chatCompletions(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/openai/chat/completions`, body);
    }

    /**
     * Get the embeddings of any arbitrary text string. This will use the embedder provider set in the system. Please ensure the token length of each string fits within the context of your embedder model.
     * @see POST /v1/openai/embeddings
     */
    async createEmbedding(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/openai/embeddings`, body);
    }

    /**
     * List all the vector database collections connected to RealTimeX. These are essentially workspaces but return their unique vector db identifier - this is the same as the workspace slug.
     * @see GET /v1/openai/vector_stores
     */
    async listVectorStores(): Promise<unknown> {
        return this.client.request('GET', `/v1/openai/vector_stores`);
    }
}
