// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 1018f7f1fd928ad4
// Tag: Runtime Sessions

import { DeveloperApiClient } from '../client';

export class V1RuntimeSessionsModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Resolve the desktop shell launch working directory for a workspace or thread context.
     * @see POST /runtime-sessions/desktop-shell/launch-spec
     */
    async desktopShellLaunchSpec(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/desktop-shell/launch-spec`, body);
    }

    /**
     * Evaluate the runtime terminal permission policy for a pending CLI action.
     * @see POST /runtime-sessions/terminal-permissions/evaluate
     */
    async terminalPermissionsEvaluate(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/terminal-permissions/evaluate`, body);
    }

    /**
     * Resolve the CLI agent terminal launch command and working directory.
     * @see POST /runtime-sessions/cli-agent/launch-spec
     */
    async cliAgentLaunchSpec(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/cli-agent/launch-spec`, body);
    }

    /**
     * Create a persistent ACP-backed CLI agent runtime session.
     * @see POST /runtime-sessions/cli-agent
     */
    async cliAgent(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/cli-agent`, body);
    }

    /**
     * Stream a chat turn to an existing CLI agent runtime session using Server-Sent Events.
     * @see POST /runtime-sessions/cli-agent/{sessionKey}/chat/stream
     */
    async cliAgentChatStream(sessionKey: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/cli-agent/${sessionKey}/chat/stream`, body);
    }

    /**
     * Resolve a pending permission request for a CLI agent runtime session.
     * @see POST /runtime-sessions/cli-agent/{sessionKey}/permission
     */
    async cliAgentPermission(sessionKey: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/cli-agent/${sessionKey}/permission`, body);
    }

    /**
     * Cancel the current CLI turn for an active runtime session.
     * @see POST /runtime-sessions/cli-agent/{sessionKey}/cancel
     */
    async cliAgentCancel(sessionKey: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/runtime-sessions/cli-agent/${sessionKey}/cancel`, body);
    }

    /**
     * Close a CLI agent runtime session and clear its control-plane metadata.
     * @see DELETE /runtime-sessions/cli-agent/{sessionKey}
     */
    async deleteCliAgent(sessionKey: string): Promise<unknown> {
        return this.client.request('DELETE', `/runtime-sessions/cli-agent/${sessionKey}`);
    }

    /**
     * Fetch the current state and runtime options for a CLI agent session.
     * @see GET /runtime-sessions/cli-agent/{sessionKey}
     */
    async getCliAgent(sessionKey: string): Promise<unknown> {
        return this.client.request('GET', `/runtime-sessions/cli-agent/${sessionKey}`);
    }
}
