// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: STT

import { DeveloperApiClient } from '../client';

export class V1SttApiModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /** @see POST /v1/stt/groq/transcribe */
    async groqTranscribe(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/stt/groq/transcribe`, body);
    }
}
