// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 1018f7f1fd928ad4
// Tag: System Settings

import { DeveloperApiClient } from '../client';

export class V1SystemModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Dump all settings to file storage
     * @see GET /v1/system/env-dump
     */
    async getEnvDump(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/env-dump`);
    }

    /**
     * Get all current system settings that are defined.
     * @see GET /v1/system
     */
    async getSystem(): Promise<unknown> {
        return this.client.request('GET', `/v1/system`);
    }

    /**
     * Number of all vectors in connected vector database
     * @see GET /v1/system/vector-count
     */
    async getVectorCount(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/vector-count`);
    }

    /**
     * Update a system setting or preference.
     * @see POST /v1/system/update-env
     */
    async updateEnv(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/system/update-env`, body);
    }

    /**
     * Export all of the chats from the system in a known format. Output depends on the type sent. Will be send with the correct header for the output.
     * @see GET /v1/system/export-chats
     */
    async listExportChats(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/export-chats`);
    }

    /**
     * Permanently remove documents from the system.
     * @see DELETE /v1/system/remove-documents
     */
    async deleteRemoveDocument(): Promise<unknown> {
        return this.client.request('DELETE', `/v1/system/remove-documents`);
    }

    /**
     * Returns a health check object with server uptime and version.
     * @see GET /v1/system/health
     */
    async getHealth(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/health`);
    }

    /**
     * Returns a health check object with server uptime and version.
     * @see GET /v1/system/health-version-2
     */
    async getHealthVersion2(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/health-version-2`);
    }

    /**
     * Returns a health check object with server uptime and version.
     * @see GET /v1/system/health-version-3
     */
    async getHealthVersion3(): Promise<unknown> {
        return this.client.request('GET', `/v1/system/health-version-3`);
    }
}
