// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 6e1eed2d292acbcc
// Tag: Workspace Threads

import { DeveloperApiClient } from '../client';

export class V1ThreadModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Create a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/new
     */
    async createThread(slug: string): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/new`);
    }

    /**
     * List workspace threads.
     * @see GET /v1/workspace/{slug}/threads
     */
    async listThreads(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/threads`);
    }

    /**
     * Open an SSE stream for workspace thread events.
     * @see GET /v1/workspace/{slug}/thread-events
     */
    async openThreadEventsStream(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread-events`);
    }

    /**
     * Get a workspace thread.
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}
     */
    async getThread(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}`);
    }

    /**
     * Delete a workspace thread.
     * @see DELETE /v1/workspace/{slug}/thread/{threadSlug}
     */
    async deleteThread(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/thread/${threadSlug}`);
    }

    /**
     * Get thread vision availability.
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}/vision-availability
     */
    async getThreadVisionAvailability(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}/vision-availability`);
    }

    /**
     * Promote a thread into a tracked goal.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/goal
     */
    async createThreadGoal(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/goal`, body);
    }

    /**
     * Draft a terminal goal for a workspace.
     * @see POST /v1/workspace/{slug}/terminal-goal-draft
     */
    async draftWorkspaceTerminalGoal(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/terminal-goal-draft`, body);
    }

    /**
     * Create a terminal goal for a workspace.
     * @see POST /v1/workspace/{slug}/terminal-goal
     */
    async createWorkspaceTerminalGoal(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/terminal-goal`, body);
    }

    /**
     * Draft a terminal goal for a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-goal-draft
     */
    async draftThreadTerminalGoal(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/terminal-goal-draft`, body);
    }

    /**
     * Create a terminal goal for a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-goal
     */
    async createThreadTerminalGoal(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/terminal-goal`, body);
    }

    /**
     * Bulk delete workspace threads.
     * @see DELETE /v1/workspace/{slug}/thread-bulk-delete
     */
    async bulkDeleteThreads(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/thread-bulk-delete`, body);
    }

    /**
     * Get workspace thread chats.
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}/chats
     */
    async getThreadChats(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}/chats`);
    }

    /**
     * Get thread terminal session details.
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}/terminal-session-details
     */
    async getThreadTerminalSessionDetails(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}/terminal-session-details`);
    }

    /**
     * Update a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/update
     */
    async updateThread(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/update`, body);
    }

    /**
     * Delete edited chats from a thread.
     * @see DELETE /v1/workspace/{slug}/thread/{threadSlug}/delete-edited-chats
     */
    async deleteEditedThreadChats(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/thread/${threadSlug}/delete-edited-chats`, body);
    }

    /**
     * Update a thread chat response.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/update-chat
     */
    async updateThreadChat(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/update-chat`, body);
    }

    /**
     * Persist terminal UI events for a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-ui-events
     */
    async persistThreadTerminalUiEvents(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/terminal-ui-events`, body);
    }

    /**
     * Persist a linked terminal message for a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/linked-terminal-message
     */
    async createThreadLinkedTerminalMessage(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/linked-terminal-message`, body);
    }

    /**
     * Coordinate a task into a workspace thread.
     * @see POST /v1/workspace/{slug}/thread/coordinate-task
     */
    async coordinateThreadTask(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/coordinate-task`, body);
    }

    /**
     * Open an SSE stream for external workspace thread chat events.
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}/chat-stream
     */
    async openThreadChatStream(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}/chat-stream`);
    }
}
