// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: a3f413c534e48228
// Tag: Workspace Threads

import { DeveloperApiClient } from '../client';

export class V1ThreadModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Create a new workspace thread
     * @see POST /v1/workspace/{slug}/thread/new
     */
    async createThread(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/new`, body);
    }

    /**
     * Update thread name by its unique slug.
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/update
     */
    async updateThread(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/update`, body);
    }

    /**
     * Delete a workspace thread
     * @see DELETE /v1/workspace/{slug}/thread/{threadSlug}
     */
    async deleteThread(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/thread/${threadSlug}`);
    }

    /**
     * Get chats for a workspace thread
     * @see GET /v1/workspace/{slug}/thread/{threadSlug}/chats
     */
    async listChats(slug: string, threadSlug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/thread/${threadSlug}/chats`);
    }

    /**
     * Chat with a workspace thread
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/chat
     */
    async chat(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/${threadSlug}/chat`, body);
    }

    /**
     * Stream chat with a workspace thread
     * @see POST /v1/workspace/{slug}/thread/{threadSlug}/stream-chat
     */
    // @streaming-stub — implement SSE parsing in overrides/v1ThreadStreaming.ts
    async streamChat(slug: string, threadSlug: string, body?: Record<string, unknown>): Promise<Response> {
        return this.client.requestRaw('POST', `/v1/workspace/${slug}/thread/${threadSlug}/stream-chat`, body);
    }
}
