// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 43c4c5a2e59c85e9
// Tag: User Management

import { DeveloperApiClient } from '../client';

export class V1UsersModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * List all users
     * @see GET /v1/users
     */
    async listUsers(): Promise<unknown> {
        return this.client.request('GET', `/v1/users`);
    }

    /**
     * Issue a temporary auth token for a user
     * @see GET /v1/users/{id}/issue-auth-token
     */
    async getIssueAuthToken(id: string): Promise<unknown> {
        return this.client.request('GET', `/v1/users/${id}/issue-auth-token`);
    }
}
