// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 43c4c5a2e59c85e9
// Tag: Workspaces

import { DeveloperApiClient } from '../client';

export class V1WorkspaceModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * Create a new workspace
     * @see POST /v1/workspace/new
     */
    async createWorkspace(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/new`, body);
    }

    /**
     * List all current workspaces
     * @see GET /v1/workspaces
     */
    async listWorkspaces(): Promise<unknown> {
        return this.client.request('GET', `/v1/workspaces`);
    }

    /**
     * Get a workspace by its unique slug.
     * @see GET /v1/workspace/{slug}
     */
    async getWorkspace(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}`);
    }

    /**
     * Deletes a workspace by its slug.
     * @see DELETE /v1/workspace/{slug}
     */
    async deleteWorkspace(slug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}`);
    }

    /**
     * Update workspace settings by its unique slug.
     * @see POST /v1/workspace/{slug}/update
     */
    async updateWorkspace(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update`, body);
    }

    /**
     * Get a workspaces chats regardless of user by its unique slug.
     * @see GET /v1/workspace/{slug}/chats
     */
    async listChats(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/chats`);
    }

    /**
     * Add or remove documents from a workspace by its unique slug.
     * @see POST /v1/workspace/{slug}/update-embeddings
     */
    async updateEmbeddings(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update-embeddings`, body);
    }

    /**
     * Add or remove pin from a document in a workspace by its unique slug.
     * @see POST /v1/workspace/{slug}/update-pin
     */
    async updatePin(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update-pin`, body);
    }

    /**
     * Execute a chat with a workspace
     * @see POST /v1/workspace/{slug}/chat
     */
    async chat(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/chat`, body);
    }

    /**
     * Execute a streamable chat with a workspace
     * @see POST /v1/workspace/{slug}/stream-chat
     */
    // @streaming-stub — implement SSE parsing in overrides/v1WorkspaceStreaming.ts
    async streamChat(slug: string, body?: Record<string, unknown>): Promise<Response> {
        return this.client.requestRaw('POST', `/v1/workspace/${slug}/stream-chat`, body);
    }

    /**
     * Perform a vector similarity search in a workspace
     * @see POST /v1/workspace/{slug}/vector-search
     */
    async vectorSearch(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/vector-search`, body);
    }
}
