// AUTO-GENERATED from openapi.json — do not edit this file directly.
// Re-run: node scripts/generate-v1-sdk.mjs
// Spec digest: 6e1eed2d292acbcc
// Tag: Workspaces

import { DeveloperApiClient } from '../client';

export class V1WorkspaceModule {
    constructor(private readonly client: DeveloperApiClient) {}
    /**
     * List workspaces using the app workspace list behavior.
     * @see GET /v1/workspaces
     */
    async listWorkspaces(): Promise<unknown> {
        return this.client.request('GET', `/v1/workspaces`);
    }

    /**
     * Create a workspace using the app workspace creation behavior.
     * @see POST /v1/workspace/new
     */
    async createWorkspace(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/new`, body);
    }

    /**
     * Search workspaces and threads.
     * @see POST /v1/workspace/search
     */
    async searchWorkspaces(body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/search`, body);
    }

    /**
     * Get a workspace by slug.
     * @see GET /v1/workspace/{slug}
     */
    async getWorkspace(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}`);
    }

    /**
     * Delete a workspace.
     * @see DELETE /v1/workspace/{slug}
     */
    async deleteWorkspace(slug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}`);
    }

    /**
     * Get document content for a workspace document.
     * @see GET /v1/workspace/{slug}/document/{docPath}
     */
    async getWorkspaceDocument(slug: string, docPath: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/document/${docPath}`);
    }

    /**
     * Get or create workspace config.
     * @see GET /v1/workspace/{slug}/config
     */
    async getWorkspaceConfig(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/config`);
    }

    /**
     * Update workspace config.
     * @see POST /v1/workspace/{slug}/config
     */
    async updateWorkspaceConfig(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/config`, body);
    }

    /**
     * Update workspace settings by slug.
     * @see POST /v1/workspace/{slug}/update
     */
    async updateWorkspace(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update`, body);
    }

    /**
     * Generate a local LLM tuning suggestion.
     * @see POST /v1/workspace/{slug}/local-llm-tuning-suggestion
     */
    async suggestWorkspaceLocalLlmTuning(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/local-llm-tuning-suggestion`, body);
    }

    /**
     * Upload a document to workspace documents.
     * @see POST /v1/workspace/{slug}/upload
     */
    // @upload-stub — multipart upload; wire form manually or use helper
    async uploadWorkspaceDocument(slug: string, form: FormData): Promise<unknown> {
        return this.client.requestMultipart('POST', `/v1/workspace/${slug}/upload`, form);
    }

    /**
     * Upload a link to workspace documents.
     * @see POST /v1/workspace/{slug}/upload-link
     */
    async uploadWorkspaceLink(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/upload-link`, body);
    }

    /**
     * Update workspace document embeddings.
     * @see POST /v1/workspace/{slug}/update-embeddings
     */
    async updateWorkspaceEmbeddings(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update-embeddings`, body);
    }

    /**
     * Reset workspace vector database records.
     * @see DELETE /v1/workspace/{slug}/reset-vector-db
     */
    async resetWorkspaceVectorDb(slug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/reset-vector-db`);
    }

    /**
     * Get workspace LLM provider metadata.
     * @see GET /v1/workspace/{slug}/llm-provider
     */
    async getWorkspaceLlmProvider(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/llm-provider`);
    }

    /**
     * Get workspace vision availability.
     * @see GET /v1/workspace/{slug}/vision-availability
     */
    async getWorkspaceVisionAvailability(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/vision-availability`);
    }

    /**
     * Get workspace chats.
     * @see GET /v1/workspace/{slug}/chats
     */
    async getWorkspaceChats(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/chats`);
    }

    /**
     * Get workspace terminal session details.
     * @see GET /v1/workspace/{slug}/terminal-session-details
     */
    async getWorkspaceTerminalSessionDetails(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/terminal-session-details`);
    }

    /**
     * Persist terminal UI events.
     * @see POST /v1/workspace/{slug}/terminal-ui-events
     */
    async persistWorkspaceTerminalUiEvents(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/terminal-ui-events`, body);
    }

    /**
     * Persist a linked terminal message.
     * @see POST /v1/workspace/{slug}/linked-terminal-message
     */
    async createWorkspaceLinkedTerminalMessage(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/linked-terminal-message`, body);
    }

    /**
     * Delete selected workspace chats.
     * @see DELETE /v1/workspace/{slug}/delete-chats
     */
    async deleteWorkspaceChats(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/delete-chats`, body);
    }

    /**
     * Delete edited workspace chats from a starting id.
     * @see DELETE /v1/workspace/{slug}/delete-edited-chats
     */
    async deleteEditedWorkspaceChats(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/delete-edited-chats`, body);
    }

    /**
     * Update a workspace chat response.
     * @see POST /v1/workspace/{slug}/update-chat
     */
    async updateWorkspaceChat(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update-chat`, body);
    }

    /**
     * Update workspace chat feedback.
     * @see POST /v1/workspace/{slug}/chat-feedback/{chatId}
     */
    async updateWorkspaceChatFeedback(slug: string, chatId: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/chat-feedback/${chatId}`, body);
    }

    /**
     * Get suggested messages for a workspace.
     * @see GET /v1/workspace/{slug}/suggested-messages
     */
    async getWorkspaceSuggestedMessages(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/suggested-messages`);
    }

    /**
     * Save suggested messages for a workspace.
     * @see POST /v1/workspace/{slug}/suggested-messages
     */
    async saveWorkspaceSuggestedMessages(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/suggested-messages`, body);
    }

    /**
     * Update workspace document pin status.
     * @see POST /v1/workspace/{slug}/update-pin
     */
    async updateWorkspaceDocumentPin(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/update-pin`, body);
    }

    /**
     * Generate text-to-speech audio for a workspace chat.
     * @see GET /v1/workspace/{slug}/tts/{chatId}
     */
    async getWorkspaceChatTts(slug: string, chatId: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/tts/${chatId}`);
    }

    /**
     * Get a workspace profile picture.
     * @see GET /v1/workspace/{slug}/pfp
     */
    async getWorkspaceProfilePicture(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/pfp`);
    }

    /**
     * Upload a workspace profile picture.
     * @see POST /v1/workspace/{slug}/upload-pfp
     */
    // @upload-stub — multipart upload; wire form manually or use helper
    async uploadWorkspaceProfilePicture(slug: string, form: FormData): Promise<unknown> {
        return this.client.requestMultipart('POST', `/v1/workspace/${slug}/upload-pfp`, form);
    }

    /**
     * Remove a workspace profile picture.
     * @see DELETE /v1/workspace/{slug}/remove-pfp
     */
    async removeWorkspaceProfilePicture(slug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/remove-pfp`);
    }

    /**
     * Fork the workspace default thread.
     * @see POST /v1/workspace/{slug}/thread/fork
     */
    async forkThread(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/thread/fork`, body);
    }

    /**
     * Hide a workspace chat.
     * @see PUT /v1/workspace/workspace-chats/{id}
     */
    async hideWorkspaceChat(id: string): Promise<unknown> {
        return this.client.request('PUT', `/v1/workspace/workspace-chats/${id}`);
    }

    /**
     * Upload and embed a document.
     * @see POST /v1/workspace/{slug}/upload-and-embed
     */
    // @upload-stub — multipart upload; wire form manually or use helper
    async uploadAndEmbedWorkspaceDocument(slug: string, form: FormData): Promise<unknown> {
        return this.client.requestMultipart('POST', `/v1/workspace/${slug}/upload-and-embed`, form);
    }

    /**
     * Remove and unembed a document.
     * @see DELETE /v1/workspace/{slug}/remove-and-unembed
     */
    async removeAndUnembedWorkspaceDocument(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/remove-and-unembed`, body);
    }

    /**
     * Get workspace prompt history.
     * @see GET /v1/workspace/{slug}/prompt-history
     */
    async getWorkspacePromptHistory(slug: string): Promise<unknown> {
        return this.client.request('GET', `/v1/workspace/${slug}/prompt-history`);
    }

    /**
     * Clear workspace prompt history.
     * @see DELETE /v1/workspace/{slug}/prompt-history
     */
    async deleteWorkspacePromptHistory(slug: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/prompt-history`);
    }

    /**
     * Delete a workspace prompt history entry.
     * @see DELETE /v1/workspace/{slug}/prompt-history/{id}
     */
    async deleteWorkspacePromptHistoryEntry(slug: string, id: string): Promise<unknown> {
        return this.client.request('DELETE', `/v1/workspace/${slug}/prompt-history/${id}`);
    }

    /**
     * Validate search provider configuration.
     * @see POST /v1/workspace/{slug}/search/validate
     */
    async validateWorkspaceSearchProvider(slug: string, body?: Record<string, unknown>): Promise<unknown> {
        return this.client.request('POST', `/v1/workspace/${slug}/search/validate`, body);
    }
}
