# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: Authentication

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1AuthModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_auth(self) -> Any:
        """Verify the attached Authentication header contains a valid API token.  GET /v1/auth"""
        return await self._client.request("GET", "/v1/auth")
