# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: f32dab4b444ad282
# Tag: Admin

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1AdminModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_is_multi_user_mode(self) -> Any:
        """Check to see if the instance is in multi-user-mode first. Methods are disabled until multi user mode is enabled via the UI.  GET /v1/admin/is-multi-user-mode"""
        return await self._client.request("GET", "/v1/admin/is-multi-user-mode")

    async def list_users(self) -> Any:
        """Check to see if the instance is in multi-user-mode first. Methods are disabled until multi user mode is enabled via the UI.  GET /v1/admin/users"""
        return await self._client.request("GET", "/v1/admin/users")

    async def create_user(self, body: dict | None = None) -> Any:
        """Create a new user with username and password. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/users/new"""
        return await self._client.request("POST", "/v1/admin/users/new", json=body)

    async def update_user(self, id: str, body: dict | None = None) -> Any:
        """Update existing user settings. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/users/{id}"""
        return await self._client.request("POST", f"/v1/admin/users/{id}", json=body)

    async def delete_user(self, id: str) -> Any:
        """Delete existing user by id. Methods are disabled until multi user mode is enabled via the UI.  DELETE /v1/admin/users/{id}"""
        return await self._client.request("DELETE", f"/v1/admin/users/{id}")

    async def list_invites(self) -> Any:
        """List all existing invitations to instance regardless of status. Methods are disabled until multi user mode is enabled via the UI.  GET /v1/admin/invites"""
        return await self._client.request("GET", "/v1/admin/invites")

    async def create_invite(self, body: dict | None = None) -> Any:
        """Create a new invite code for someone to use to register with instance. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/invite/new"""
        return await self._client.request("POST", "/v1/admin/invite/new", json=body)

    async def delete_invite(self, id: str) -> Any:
        """Deactivates (soft-delete) invite by id. Methods are disabled until multi user mode is enabled via the UI.  DELETE /v1/admin/invite/{id}"""
        return await self._client.request("DELETE", f"/v1/admin/invite/{id}")

    async def list_workspace_users(self, workspace_id: str) -> Any:
        """Retrieve a list of users with permissions to access the specified workspace.  GET /v1/admin/workspaces/{workspaceId}/users"""
        return await self._client.request("GET", f"/v1/admin/workspaces/{workspace_id}/users")

    async def update_users(self, workspace_id: str, body: dict | None = None) -> Any:
        """Overwrite workspace permissions to only be accessible by the given user ids and admins. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/workspaces/{workspaceId}/update-users"""
        return await self._client.request("POST", f"/v1/admin/workspaces/{workspace_id}/update-users", json=body)

    async def workspaces_manage_users(self, workspace_slug: str, body: dict | None = None) -> Any:
        """Set workspace permissions to be accessible by the given user ids and admins. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/workspaces/{workspaceSlug}/manage-users"""
        return await self._client.request("POST", f"/v1/admin/workspaces/{workspace_slug}/manage-users", json=body)

    async def workspace_chats(self, body: dict | None = None) -> Any:
        """All chats in the system ordered by most recent. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/workspace-chats"""
        return await self._client.request("POST", "/v1/admin/workspace-chats", json=body)

    async def create_preference(self, body: dict | None = None) -> Any:
        """Update multi-user preferences for instance. Methods are disabled until multi user mode is enabled via the UI.  POST /v1/admin/preferences"""
        return await self._client.request("POST", "/v1/admin/preferences", json=body)
