# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 4bf39d5450c53d1c
# Tag: Authentication

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1AuthModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_auth(self) -> Any:
        """Verify the attached Authentication header contains a valid API token.  GET /v1/auth"""
        return await self._client.request("GET", "/v1/auth")

    async def external_callback(self) -> Any:
        """Relay external browser auth callbacks back to the local Electron renderer. Localhost only; keyed by OAuth state.  POST /v1/auth/external-callback"""
        return await self._client.request("POST", "/v1/auth/external-callback")

    async def get_external_callback(self, state: str) -> Any:
        """Poll for a relayed external browser auth callback by OAuth state. Localhost only.  GET /v1/auth/external-callback/{state}"""
        return await self._client.request("GET", f"/v1/auth/external-callback/{state}")
