# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: ACP Commands

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1AcpCommandsModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def create_command(self) -> Any:
        """POST /v1/acp/command"""
        return await self._client.request("POST", "/v1/acp/command")

    async def permission_decision(self) -> Any:
        """POST /v1/acp/command/permission-decision"""
        return await self._client.request("POST", "/v1/acp/command/permission-decision")
