# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: ACP Auth

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1AcpAuthModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_profiles(self) -> Any:
        """GET /v1/acp/auth/profiles"""
        return await self._client.request("GET", "/v1/acp/auth/profiles")

    async def create_profile(self) -> Any:
        """POST /v1/acp/auth/profiles"""
        return await self._client.request("POST", "/v1/acp/auth/profiles")

    async def get_status(self) -> Any:
        """GET /v1/acp/auth/status"""
        return await self._client.request("GET", "/v1/acp/auth/status")

    async def delete_profile(self, id: str) -> Any:
        """DELETE /v1/acp/auth/profiles/{id}"""
        return await self._client.request("DELETE", f"/v1/acp/auth/profiles/{id}")
