# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 6e1eed2d292acbcc
# Tag: Chat

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1ChatModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    # @streaming-stub — implement SSE parsing in overrides/v1_chat_streaming.py
    async def stream_workspace_chat(self, slug: str, body: dict | None = None) -> Any:
        """Stream a chat response for a workspace default thread.  POST /v1/workspace/{slug}/stream-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/stream-chat", json=body)

    # @streaming-stub — implement SSE parsing in overrides/v1_chat_streaming.py
    async def stream_thread_chat(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Stream a chat response for a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/stream-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/stream-chat", json=body)
