# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: Credentials

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1CredentialsModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def create_credential(self) -> Any:
        """POST /v1/credentials"""
        return await self._client.request("POST", "/v1/credentials")

    async def list_credentials(self) -> Any:
        """GET /v1/credentials"""
        return await self._client.request("GET", "/v1/credentials")

    async def get_credential(self, id: str) -> Any:
        """GET /v1/credentials/{id}"""
        return await self._client.request("GET", f"/v1/credentials/{id}")

    async def replace_credential(self, id: str) -> Any:
        """PUT /v1/credentials/{id}"""
        return await self._client.request("PUT", f"/v1/credentials/{id}")

    async def delete_credential(self, id: str) -> Any:
        """DELETE /v1/credentials/{id}"""
        return await self._client.request("DELETE", f"/v1/credentials/{id}")

    async def restore(self, id: str) -> Any:
        """POST /v1/credentials/{id}/restore"""
        return await self._client.request("POST", f"/v1/credentials/{id}/restore")
