# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: Custom Themes

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1CustomThemesModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_custom_themes(self) -> Any:
        """GET /v1/custom-themes"""
        return await self._client.request("GET", "/v1/custom-themes")

    async def get_custom_theme(self, id: str) -> Any:
        """GET /v1/custom-themes/{id}"""
        return await self._client.request("GET", f"/v1/custom-themes/{id}")

    async def update_custom_theme(self, id: str) -> Any:
        """POST /v1/custom-themes/{id}"""
        return await self._client.request("POST", f"/v1/custom-themes/{id}")

    async def delete_custom_theme(self, id: str) -> Any:
        """DELETE /v1/custom-themes/{id}"""
        return await self._client.request("DELETE", f"/v1/custom-themes/{id}")

    async def create_custom_theme(self) -> Any:
        """POST /v1/custom-themes/new"""
        return await self._client.request("POST", "/v1/custom-themes/new")
