# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 146edc2864715e5d
# Tag: Channels

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1ChannelsModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_plugins(self) -> Any:
        """List configured channel plugins without exposing encrypted plugin configuration.  GET /v1/channels/plugins"""
        return await self._client.request("GET", "/v1/channels/plugins")

    async def create_plugin(self, body: dict | None = None) -> Any:
        """Create a channel plugin. The request may include provider credentials in config, but credentials are never returned.  POST /v1/channels/plugins"""
        return await self._client.request("POST", "/v1/channels/plugins", json=body)

    async def get_config(self, id: str) -> Any:
        """Get editable non-secret channel plugin configuration.  GET /v1/channels/plugins/{id}/config"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/config")

    async def update_plugin(self, id: str, body: dict | None = None) -> Any:
        """Update a channel plugin. Config values are encrypted before storage.  POST /v1/channels/plugins/{id}/update"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/update", json=body)

    async def delete_plugin(self, id: str) -> Any:
        """Delete a channel plugin and stop any running plugin instance.  DELETE /v1/channels/plugins/{id}"""
        return await self._client.request("DELETE", f"/v1/channels/plugins/{id}")

    async def plugins_start(self, id: str) -> Any:
        """Enable and start a channel plugin.  POST /v1/channels/plugins/{id}/start"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/start")

    async def plugins_stop(self, id: str) -> Any:
        """Disable and stop a channel plugin.  POST /v1/channels/plugins/{id}/stop"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/stop")

    async def plugins_test(self, body: dict | None = None) -> Any:
        """Test channel provider credentials without saving a plugin.  POST /v1/channels/plugins/test"""
        return await self._client.request("POST", "/v1/channels/plugins/test", json=body)

    async def get_status(self) -> Any:
        """Get runtime status for all running channel plugins.  GET /v1/channels/status"""
        return await self._client.request("GET", "/v1/channels/status")

    async def plugins_qr_login_start(self, id: str, body: dict | None = None) -> Any:
        """Start a QR login flow for Zalo personal or WhatsApp plugins.  POST /v1/channels/plugins/{id}/qr-login/start"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/qr-login/start", json=body)

    async def get_state(self, id: str) -> Any:
        """Poll QR login status for Zalo personal or WhatsApp plugins.  GET /v1/channels/plugins/{id}/qr-login/state"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/qr-login/state")

    async def plugins_qr_login_cancel(self, id: str) -> Any:
        """Cancel a QR login flow for Zalo personal or WhatsApp plugins.  POST /v1/channels/plugins/{id}/qr-login/cancel"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/qr-login/cancel")

    async def plugins_logout(self, id: str) -> Any:
        """Log out a QR-authenticated Zalo personal or WhatsApp plugin and clear stored credentials.  POST /v1/channels/plugins/{id}/logout"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/logout")

    async def plugins_policies(self, id: str, body: dict | None = None) -> Any:
        """Update safe channel policies for Zalo personal or WhatsApp plugins without overwriting credentials.  POST /v1/channels/plugins/{id}/policies"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/policies", json=body)

    async def list_directory_friends(self, id: str) -> Any:
        """Search a Zalo personal friends directory.  GET /v1/channels/plugins/{id}/directory/friends"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/directory/friends")

    async def list_directory_groups(self, id: str) -> Any:
        """Search a Zalo personal groups directory.  GET /v1/channels/plugins/{id}/directory/groups"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/directory/groups")

    async def list_plugin_pairing_codes(self, id: str) -> Any:
        """List pending pairing codes for a channel plugin.  GET /v1/channels/plugins/{id}/pairing-codes"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/pairing-codes")

    async def plugins_pairing_codes(self, id: str, body: dict | None = None) -> Any:
        """Generate a pairing code for a channel plugin.  POST /v1/channels/plugins/{id}/pairing-codes"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/pairing-codes", json=body)

    async def pairing_codes_approve(self, id: str) -> Any:
        """Approve a channel pairing code.  POST /v1/channels/pairing-codes/{id}/approve"""
        return await self._client.request("POST", f"/v1/channels/pairing-codes/{id}/approve")

    async def pairing_codes_reject(self, id: str) -> Any:
        """Reject a channel pairing code.  POST /v1/channels/pairing-codes/{id}/reject"""
        return await self._client.request("POST", f"/v1/channels/pairing-codes/{id}/reject")

    async def list_plugin_users(self, id: str) -> Any:
        """List channel users for a plugin.  GET /v1/channels/plugins/{id}/users"""
        return await self._client.request("GET", f"/v1/channels/plugins/{id}/users")

    async def plugins_users_authorization(self, id: str, user_id: str, body: dict | None = None) -> Any:
        """Set authorization for a channel user.  POST /v1/channels/plugins/{id}/users/{userId}/authorization"""
        return await self._client.request("POST", f"/v1/channels/plugins/{id}/users/{user_id}/authorization", json=body)

    async def delete_user(self, id: str, user_id: str) -> Any:
        """Remove a channel user from a plugin.  DELETE /v1/channels/plugins/{id}/users/{userId}"""
        return await self._client.request("DELETE", f"/v1/channels/plugins/{id}/users/{user_id}")
