# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: Desktop Embed

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1DesktopEmbedModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_status(self) -> Any:
        """GET /v1/desktop-public-embed/status"""
        return await self._client.request("GET", "/v1/desktop-public-embed/status")

    async def create_exposure(self) -> Any:
        """POST /v1/desktop-public-embed/exposures"""
        return await self._client.request("POST", "/v1/desktop-public-embed/exposures")

    async def exposures_heartbeat(self, exposure_id: str) -> Any:
        """POST /v1/desktop-public-embed/exposures/{exposureId}/heartbeat"""
        return await self._client.request("POST", f"/v1/desktop-public-embed/exposures/{exposure_id}/heartbeat")

    async def get_exposure(self, exposure_id: str) -> Any:
        """GET /v1/desktop-public-embed/exposures/{exposureId}"""
        return await self._client.request("GET", f"/v1/desktop-public-embed/exposures/{exposure_id}")

    async def delete_exposure(self, exposure_id: str) -> Any:
        """DELETE /v1/desktop-public-embed/exposures/{exposureId}"""
        return await self._client.request("DELETE", f"/v1/desktop-public-embed/exposures/{exposure_id}")
