# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 43c4c5a2e59c85e9
# Tag: SDK - Desktop Runtime Sessions

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1DesktopRuntimeSessionsModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def open_launcher(self, body: dict | None = None) -> Any:
        """Open the shared terminal launcher in the Electron desktop app.  POST /sdk/desktop/runtime-sessions/open-launcher"""
        return await self._client.request("POST", "/sdk/desktop/runtime-sessions/open-launcher", json=body)

    async def launch_terminal_shell(self, body: dict | None = None) -> Any:
        """Launch a local PTY-backed shell terminal in the Electron desktop app.  POST /sdk/desktop/runtime-sessions/launch-terminal-shell"""
        return await self._client.request("POST", "/sdk/desktop/runtime-sessions/launch-terminal-shell", json=body)

    async def launch_terminal_cli_agent(self, body: dict | None = None) -> Any:
        """Launch a local PTY-backed CLI agent terminal in the Electron desktop app.  POST /sdk/desktop/runtime-sessions/launch-terminal-cli-agent"""
        return await self._client.request("POST", "/sdk/desktop/runtime-sessions/launch-terminal-cli-agent", json=body)

    async def list_runtime_sessions(self) -> Any:
        """List desktop PTY-backed runtime sessions currently known to the Electron app.  GET /sdk/desktop/runtime-sessions"""
        return await self._client.request("GET", "/sdk/desktop/runtime-sessions")

    async def get_runtime_session(self, session_id: str) -> Any:
        """Fetch one desktop PTY-backed runtime session by runtime session ID or PTY session ID.  GET /sdk/desktop/runtime-sessions/{sessionId}"""
        return await self._client.request("GET", f"/sdk/desktop/runtime-sessions/{session_id}")

    async def delete_runtime_session(self, session_id: str) -> Any:
        """Close an existing desktop runtime session.  DELETE /sdk/desktop/runtime-sessions/{sessionId}"""
        return await self._client.request("DELETE", f"/sdk/desktop/runtime-sessions/{session_id}")

    async def write(self, session_id: str, body: dict | None = None) -> Any:
        """Write input to an existing desktop runtime session. Use `message` to submit a CLI turn or `input` for raw PTY data.  POST /sdk/desktop/runtime-sessions/{sessionId}/write"""
        return await self._client.request("POST", f"/sdk/desktop/runtime-sessions/{session_id}/write", json=body)

    async def permission(self, session_id: str, body: dict | None = None) -> Any:
        """Approve or deny a pending desktop runtime session action.  POST /sdk/desktop/runtime-sessions/{sessionId}/permission"""
        return await self._client.request("POST", f"/sdk/desktop/runtime-sessions/{session_id}/permission", json=body)
