# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 1018f7f1fd928ad4
# Tag: Documents

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1DocumentModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    # @upload-stub — multipart upload
    async def upload(self, files: dict) -> Any:
        """Upload a new file to RealTimeX to be parsed and prepared for embedding.  POST /v1/document/upload"""
        return await self._client.request_multipart("POST", "/v1/document/upload", files=files)

    # @upload-stub — multipart upload
    async def upload_folder(self, folder_name: str, files: dict) -> Any:
        """Upload a new file to a specific folder in RealTimeX to be parsed and prepared for embedding. If the folder does not exist, it will be created.  POST /v1/document/upload/{folderName}"""
        return await self._client.request_multipart("POST", f"/v1/document/upload/{folder_name}", files=files)

    async def upload_link(self, body: dict | None = None) -> Any:
        """Upload a valid URL for RealTimeX to scrape and prepare for embedding. Optionally, specify a comma-separated list of workspace slugs to embed the document into post-upload.  POST /v1/document/upload-link"""
        return await self._client.request("POST", "/v1/document/upload-link", json=body)

    async def raw_text(self, body: dict | None = None) -> Any:
        """Upload a file by specifying its raw text content and metadata values without having to upload a file.  POST /v1/document/raw-text"""
        return await self._client.request("POST", "/v1/document/raw-text", json=body)

    async def list_documents(self) -> Any:
        """List of all locally-stored documents in instance  GET /v1/documents"""
        return await self._client.request("GET", "/v1/documents")

    async def get_folder(self, folder_name: str) -> Any:
        """Get all documents stored in a specific folder.  GET /v1/documents/folder/{folderName}"""
        return await self._client.request("GET", f"/v1/documents/folder/{folder_name}")

    async def list_accepted_file_types(self) -> Any:
        """Check available filetypes and MIMEs that can be uploaded.  GET /v1/document/accepted-file-types"""
        return await self._client.request("GET", "/v1/document/accepted-file-types")

    async def get_metadata_schema(self) -> Any:
        """Get the known available metadata schema for when doing a raw-text upload and the acceptable type of value for each key.  GET /v1/document/metadata-schema"""
        return await self._client.request("GET", "/v1/document/metadata-schema")

    async def get_document(self, doc_name: str) -> Any:
        """Get a single document by its unique RealTimeX document name  GET /v1/document/{docName}"""
        return await self._client.request("GET", f"/v1/document/{doc_name}")

    async def create_folder(self, body: dict | None = None) -> Any:
        """Create a new folder inside the documents storage directory.  POST /v1/document/create-folder"""
        return await self._client.request("POST", "/v1/document/create-folder", json=body)

    async def delete_remove_folder(self) -> Any:
        """Remove a folder and all its contents from the documents storage directory.  DELETE /v1/document/remove-folder"""
        return await self._client.request("DELETE", "/v1/document/remove-folder")

    async def move_files(self, body: dict | None = None) -> Any:
        """Move files within the documents storage directory.  POST /v1/document/move-files"""
        return await self._client.request("POST", "/v1/document/move-files", json=body)
