# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 4bf39d5450c53d1c
# Tag: SDK - Desktop Browser

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1DesktopBrowserModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_sessions(self) -> Any:
        """List RealTimeX Browser sessions available in the Electron desktop app.  GET /sdk/desktop/browser/sessions"""
        return await self._client.request("GET", "/sdk/desktop/browser/sessions")

    async def create_session(self, body: dict | None = None) -> Any:
        """Create a named RealTimeX Browser session in the Electron desktop app.  POST /sdk/desktop/browser/sessions"""
        return await self._client.request("POST", "/sdk/desktop/browser/sessions", json=body)

    async def get_session(self, session_name: str) -> Any:
        """Get a specific RealTimeX Browser session by session name.  GET /sdk/desktop/browser/sessions/{sessionName}"""
        return await self._client.request("GET", f"/sdk/desktop/browser/sessions/{session_name}")

    async def delete_session(self, session_name: str) -> Any:
        """Delete a named RealTimeX Browser session from the Electron desktop app.  DELETE /sdk/desktop/browser/sessions/{sessionName}"""
        return await self._client.request("DELETE", f"/sdk/desktop/browser/sessions/{session_name}")

    async def create_tab(self, body: dict | None = None) -> Any:
        """Create a RealTimeX Browser tab, optionally launching the browser session if needed.  POST /sdk/desktop/browser/tabs"""
        return await self._client.request("POST", "/sdk/desktop/browser/tabs", json=body)

    async def get_tab(self, tab_ref: str) -> Any:
        """Get a RealTimeX Browser tab snapshot by tab reference.  GET /sdk/desktop/browser/tabs/{tabRef}"""
        return await self._client.request("GET", f"/sdk/desktop/browser/tabs/{tab_ref}")

    async def delete_tab(self, tab_ref: str) -> Any:
        """Close an existing RealTimeX Browser tab.  DELETE /sdk/desktop/browser/tabs/{tabRef}"""
        return await self._client.request("DELETE", f"/sdk/desktop/browser/tabs/{tab_ref}")

    async def evaluate_tab(self, tab_ref: str, body: dict | None = None) -> Any:
        """Evaluate JavaScript in a specific RealTimeX Browser tab.  POST /sdk/desktop/browser/tabs/{tabRef}/evaluate"""
        return await self._client.request("POST", f"/sdk/desktop/browser/tabs/{tab_ref}/evaluate", json=body)

    async def focus_tab(self, tab_ref: str, body: dict | None = None) -> Any:
        """Focus an existing RealTimeX Browser tab.  POST /sdk/desktop/browser/tabs/{tabRef}/focus"""
        return await self._client.request("POST", f"/sdk/desktop/browser/tabs/{tab_ref}/focus", json=body)

    async def navigate_tab(self, tab_ref: str, body: dict | None = None) -> Any:
        """Navigate an existing RealTimeX Browser tab to a new URL.  POST /sdk/desktop/browser/tabs/{tabRef}/navigate"""
        return await self._client.request("POST", f"/sdk/desktop/browser/tabs/{tab_ref}/navigate", json=body)
