# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 146edc2864715e5d
# Tag: Embed

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1EmbedModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_embed(self) -> Any:
        """List all active embeds  GET /v1/embed"""
        return await self._client.request("GET", "/v1/embed")

    async def list_chats(self, embed_uuid: str) -> Any:
        """Get all chats for a specific embed  GET /v1/embed/{embedUuid}/chats"""
        return await self._client.request("GET", f"/v1/embed/{embed_uuid}/chats")

    async def get_chat(self, embed_uuid: str, session_uuid: str) -> Any:
        """Get chats for a specific embed and session  GET /v1/embed/{embedUuid}/chats/{sessionUuid}"""
        return await self._client.request("GET", f"/v1/embed/{embed_uuid}/chats/{session_uuid}")

    async def create_embed(self, body: dict | None = None) -> Any:
        """Create a new embed configuration  POST /v1/embed/new"""
        return await self._client.request("POST", "/v1/embed/new", json=body)

    async def update_embed(self, embed_uuid: str, body: dict | None = None) -> Any:
        """Update an existing embed configuration  POST /v1/embed/{embedUuid}"""
        return await self._client.request("POST", f"/v1/embed/{embed_uuid}", json=body)

    async def delete_embed(self, embed_uuid: str) -> Any:
        """Delete an existing embed configuration  DELETE /v1/embed/{embedUuid}"""
        return await self._client.request("DELETE", f"/v1/embed/{embed_uuid}")
