# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 057cb7eca109fe06
# Tag: OpenAI Compatible Endpoints

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1OpenAIModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_models(self) -> Any:
        """Get all available "models" which are workspaces you can use for chatting.  GET /v1/openai/models"""
        return await self._client.request("GET", "/v1/openai/models")

    async def chat_completions(self, body: dict | None = None) -> Any:
        """Execute a chat with a workspace with OpenAI compatibility. Supports streaming as well. Model must be a workspace slug from /models.  POST /v1/openai/chat/completions"""
        return await self._client.request("POST", "/v1/openai/chat/completions", json=body)

    async def create_embedding(self, body: dict | None = None) -> Any:
        """Get the embeddings of any arbitrary text string. This will use the embedder provider set in the system. Please ensure the token length of each string fits within the context of your embedder model.  POST /v1/openai/embeddings"""
        return await self._client.request("POST", "/v1/openai/embeddings", json=body)

    async def list_vector_stores(self) -> Any:
        """List all the vector database collections connected to RealTimeX. These are essentially workspaces but return their unique vector db identifier - this is the same as the workspace slug.  GET /v1/openai/vector_stores"""
        return await self._client.request("GET", "/v1/openai/vector_stores")
