# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 1018f7f1fd928ad4
# Tag: Runtime Sessions

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1RuntimeSessionsModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def desktop_shell_launch_spec(self, body: dict | None = None) -> Any:
        """Resolve the desktop shell launch working directory for a workspace or thread context.  POST /runtime-sessions/desktop-shell/launch-spec"""
        return await self._client.request("POST", "/runtime-sessions/desktop-shell/launch-spec", json=body)

    async def terminal_permissions_evaluate(self, body: dict | None = None) -> Any:
        """Evaluate the runtime terminal permission policy for a pending CLI action.  POST /runtime-sessions/terminal-permissions/evaluate"""
        return await self._client.request("POST", "/runtime-sessions/terminal-permissions/evaluate", json=body)

    async def cli_agent_launch_spec(self, body: dict | None = None) -> Any:
        """Resolve the CLI agent terminal launch command and working directory.  POST /runtime-sessions/cli-agent/launch-spec"""
        return await self._client.request("POST", "/runtime-sessions/cli-agent/launch-spec", json=body)

    async def cli_agent(self, body: dict | None = None) -> Any:
        """Create a persistent ACP-backed CLI agent runtime session.  POST /runtime-sessions/cli-agent"""
        return await self._client.request("POST", "/runtime-sessions/cli-agent", json=body)

    async def cli_agent_chat_stream(self, session_key: str, body: dict | None = None) -> Any:
        """Stream a chat turn to an existing CLI agent runtime session using Server-Sent Events.  POST /runtime-sessions/cli-agent/{sessionKey}/chat/stream"""
        return await self._client.request("POST", f"/runtime-sessions/cli-agent/{session_key}/chat/stream", json=body)

    async def cli_agent_permission(self, session_key: str, body: dict | None = None) -> Any:
        """Resolve a pending permission request for a CLI agent runtime session.  POST /runtime-sessions/cli-agent/{sessionKey}/permission"""
        return await self._client.request("POST", f"/runtime-sessions/cli-agent/{session_key}/permission", json=body)

    async def cli_agent_cancel(self, session_key: str, body: dict | None = None) -> Any:
        """Cancel the current CLI turn for an active runtime session.  POST /runtime-sessions/cli-agent/{sessionKey}/cancel"""
        return await self._client.request("POST", f"/runtime-sessions/cli-agent/{session_key}/cancel", json=body)

    async def delete_cli_agent(self, session_key: str) -> Any:
        """Close a CLI agent runtime session and clear its control-plane metadata.  DELETE /runtime-sessions/cli-agent/{sessionKey}"""
        return await self._client.request("DELETE", f"/runtime-sessions/cli-agent/{session_key}")

    async def get_cli_agent(self, session_key: str) -> Any:
        """Fetch the current state and runtime options for a CLI agent session.  GET /runtime-sessions/cli-agent/{sessionKey}"""
        return await self._client.request("GET", f"/runtime-sessions/cli-agent/{session_key}")
