# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: STT

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1SttApiModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def groq_transcribe(self, body: dict | None = None) -> Any:
        """POST /v1/stt/groq/transcribe"""
        return await self._client.request("POST", "/v1/stt/groq/transcribe", json=body)
