# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 90a37390a78f04cb
# Tag: System Settings

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1SystemModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def get_env_dump(self) -> Any:
        """Dump all settings to file storage  GET /v1/system/env-dump"""
        return await self._client.request("GET", "/v1/system/env-dump")

    async def get_system(self) -> Any:
        """Get all current system settings that are defined.  GET /v1/system"""
        return await self._client.request("GET", "/v1/system")

    async def get_vector_count(self) -> Any:
        """Number of all vectors in connected vector database  GET /v1/system/vector-count"""
        return await self._client.request("GET", "/v1/system/vector-count")

    async def update_env(self, body: dict | None = None) -> Any:
        """Update a system setting or preference.  POST /v1/system/update-env"""
        return await self._client.request("POST", "/v1/system/update-env", json=body)

    async def list_export_chats(self) -> Any:
        """Export all of the chats from the system in a known format. Output depends on the type sent. Will be send with the correct header for the output.  GET /v1/system/export-chats"""
        return await self._client.request("GET", "/v1/system/export-chats")

    async def delete_remove_document(self) -> Any:
        """Permanently remove documents from the system.  DELETE /v1/system/remove-documents"""
        return await self._client.request("DELETE", "/v1/system/remove-documents")

    async def get_health(self) -> Any:
        """Returns a health check object with server uptime and version.  GET /v1/system/health"""
        return await self._client.request("GET", "/v1/system/health")

    async def get_health_version2(self) -> Any:
        """Returns a health check object with server uptime and version.  GET /v1/system/health-version-2"""
        return await self._client.request("GET", "/v1/system/health-version-2")

    async def get_health_version3(self) -> Any:
        """Returns a health check object with server uptime and version.  GET /v1/system/health-version-3"""
        return await self._client.request("GET", "/v1/system/health-version-3")
