# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 6e1eed2d292acbcc
# Tag: Workspace Threads

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1ThreadModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def create_thread(self, slug: str) -> Any:
        """Create a workspace thread.  POST /v1/workspace/{slug}/thread/new"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/new")

    async def list_threads(self, slug: str) -> Any:
        """List workspace threads.  GET /v1/workspace/{slug}/threads"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/threads")

    async def open_thread_events_stream(self, slug: str) -> Any:
        """Open an SSE stream for workspace thread events.  GET /v1/workspace/{slug}/thread-events"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread-events")

    async def get_thread(self, slug: str, thread_slug: str) -> Any:
        """Get a workspace thread.  GET /v1/workspace/{slug}/thread/{threadSlug}"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}")

    async def delete_thread(self, slug: str, thread_slug: str) -> Any:
        """Delete a workspace thread.  DELETE /v1/workspace/{slug}/thread/{threadSlug}"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/thread/{thread_slug}")

    async def get_thread_vision_availability(self, slug: str, thread_slug: str) -> Any:
        """Get thread vision availability.  GET /v1/workspace/{slug}/thread/{threadSlug}/vision-availability"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}/vision-availability")

    async def create_thread_goal(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Promote a thread into a tracked goal.  POST /v1/workspace/{slug}/thread/{threadSlug}/goal"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/goal", json=body)

    async def draft_workspace_terminal_goal(self, slug: str, body: dict | None = None) -> Any:
        """Draft a terminal goal for a workspace.  POST /v1/workspace/{slug}/terminal-goal-draft"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/terminal-goal-draft", json=body)

    async def create_workspace_terminal_goal(self, slug: str, body: dict | None = None) -> Any:
        """Create a terminal goal for a workspace.  POST /v1/workspace/{slug}/terminal-goal"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/terminal-goal", json=body)

    async def draft_thread_terminal_goal(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Draft a terminal goal for a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-goal-draft"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/terminal-goal-draft", json=body)

    async def create_thread_terminal_goal(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Create a terminal goal for a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-goal"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/terminal-goal", json=body)

    async def bulk_delete_threads(self, slug: str, body: dict | None = None) -> Any:
        """Bulk delete workspace threads.  DELETE /v1/workspace/{slug}/thread-bulk-delete"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/thread-bulk-delete", json=body)

    async def get_thread_chats(self, slug: str, thread_slug: str) -> Any:
        """Get workspace thread chats.  GET /v1/workspace/{slug}/thread/{threadSlug}/chats"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}/chats")

    async def get_thread_terminal_session_details(self, slug: str, thread_slug: str) -> Any:
        """Get thread terminal session details.  GET /v1/workspace/{slug}/thread/{threadSlug}/terminal-session-details"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}/terminal-session-details")

    async def update_thread(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Update a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/update"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/update", json=body)

    async def delete_edited_thread_chats(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Delete edited chats from a thread.  DELETE /v1/workspace/{slug}/thread/{threadSlug}/delete-edited-chats"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/thread/{thread_slug}/delete-edited-chats", json=body)

    async def update_thread_chat(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Update a thread chat response.  POST /v1/workspace/{slug}/thread/{threadSlug}/update-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/update-chat", json=body)

    async def persist_thread_terminal_ui_events(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Persist terminal UI events for a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/terminal-ui-events"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/terminal-ui-events", json=body)

    async def create_thread_linked_terminal_message(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Persist a linked terminal message for a workspace thread.  POST /v1/workspace/{slug}/thread/{threadSlug}/linked-terminal-message"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/linked-terminal-message", json=body)

    async def coordinate_thread_task(self, slug: str, body: dict | None = None) -> Any:
        """Coordinate a task into a workspace thread.  POST /v1/workspace/{slug}/thread/coordinate-task"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/coordinate-task", json=body)

    async def open_thread_chat_stream(self, slug: str, thread_slug: str) -> Any:
        """Open an SSE stream for external workspace thread chat events.  GET /v1/workspace/{slug}/thread/{threadSlug}/chat-stream"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}/chat-stream")
