# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: a3f413c534e48228
# Tag: Workspace Threads

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1ThreadModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def create_thread(self, slug: str, body: dict | None = None) -> Any:
        """Create a new workspace thread  POST /v1/workspace/{slug}/thread/new"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/new", json=body)

    async def update_thread(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Update thread name by its unique slug.  POST /v1/workspace/{slug}/thread/{threadSlug}/update"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/update", json=body)

    async def delete_thread(self, slug: str, thread_slug: str) -> Any:
        """Delete a workspace thread  DELETE /v1/workspace/{slug}/thread/{threadSlug}"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/thread/{thread_slug}")

    async def list_chats(self, slug: str, thread_slug: str) -> Any:
        """Get chats for a workspace thread  GET /v1/workspace/{slug}/thread/{threadSlug}/chats"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/thread/{thread_slug}/chats")

    async def chat(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Chat with a workspace thread  POST /v1/workspace/{slug}/thread/{threadSlug}/chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/chat", json=body)

    # @streaming-stub — implement SSE parsing in overrides/v1_thread_streaming.py
    async def stream_chat(self, slug: str, thread_slug: str, body: dict | None = None) -> Any:
        """Stream chat with a workspace thread  POST /v1/workspace/{slug}/thread/{threadSlug}/stream-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/{thread_slug}/stream-chat", json=body)
