# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 057cb7eca109fe06
# Tag: User Management

from __future__ import annotations
from typing import Any, Optional
from ..client import DeveloperApiClient


class V1UsersModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_users(self) -> Any:
        """List all users  GET /v1/users"""
        return await self._client.request("GET", "/v1/users")

    async def get_issue_auth_token(self, id: str) -> Any:
        """Issue a temporary auth token for a user  GET /v1/users/{id}/issue-auth-token"""
        return await self._client.request("GET", f"/v1/users/{id}/issue-auth-token")
