# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: 6e1eed2d292acbcc
# Tag: Workspaces

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1WorkspaceModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def list_workspaces(self) -> Any:
        """List workspaces using the app workspace list behavior.  GET /v1/workspaces"""
        return await self._client.request("GET", "/v1/workspaces")

    async def create_workspace(self, body: dict | None = None) -> Any:
        """Create a workspace using the app workspace creation behavior.  POST /v1/workspace/new"""
        return await self._client.request("POST", "/v1/workspace/new", json=body)

    async def search_workspaces(self, body: dict | None = None) -> Any:
        """Search workspaces and threads.  POST /v1/workspace/search"""
        return await self._client.request("POST", "/v1/workspace/search", json=body)

    async def get_workspace(self, slug: str) -> Any:
        """Get a workspace by slug.  GET /v1/workspace/{slug}"""
        return await self._client.request("GET", f"/v1/workspace/{slug}")

    async def delete_workspace(self, slug: str) -> Any:
        """Delete a workspace.  DELETE /v1/workspace/{slug}"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}")

    async def get_workspace_document(self, slug: str, doc_path: str) -> Any:
        """Get document content for a workspace document.  GET /v1/workspace/{slug}/document/{docPath}"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/document/{doc_path}")

    async def get_workspace_config(self, slug: str) -> Any:
        """Get or create workspace config.  GET /v1/workspace/{slug}/config"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/config")

    async def update_workspace_config(self, slug: str, body: dict | None = None) -> Any:
        """Update workspace config.  POST /v1/workspace/{slug}/config"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/config", json=body)

    async def update_workspace(self, slug: str, body: dict | None = None) -> Any:
        """Update workspace settings by slug.  POST /v1/workspace/{slug}/update"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update", json=body)

    async def suggest_workspace_local_llm_tuning(self, slug: str, body: dict | None = None) -> Any:
        """Generate a local LLM tuning suggestion.  POST /v1/workspace/{slug}/local-llm-tuning-suggestion"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/local-llm-tuning-suggestion", json=body)

    # @upload-stub — multipart upload
    async def upload_workspace_document(self, slug: str, files: dict) -> Any:
        """Upload a document to workspace documents.  POST /v1/workspace/{slug}/upload"""
        return await self._client.request_multipart("POST", f"/v1/workspace/{slug}/upload", files=files)

    async def upload_workspace_link(self, slug: str, body: dict | None = None) -> Any:
        """Upload a link to workspace documents.  POST /v1/workspace/{slug}/upload-link"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/upload-link", json=body)

    async def update_workspace_embeddings(self, slug: str, body: dict | None = None) -> Any:
        """Update workspace document embeddings.  POST /v1/workspace/{slug}/update-embeddings"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update-embeddings", json=body)

    async def reset_workspace_vector_db(self, slug: str) -> Any:
        """Reset workspace vector database records.  DELETE /v1/workspace/{slug}/reset-vector-db"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/reset-vector-db")

    async def get_workspace_llm_provider(self, slug: str) -> Any:
        """Get workspace LLM provider metadata.  GET /v1/workspace/{slug}/llm-provider"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/llm-provider")

    async def get_workspace_vision_availability(self, slug: str) -> Any:
        """Get workspace vision availability.  GET /v1/workspace/{slug}/vision-availability"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/vision-availability")

    async def get_workspace_chats(self, slug: str) -> Any:
        """Get workspace chats.  GET /v1/workspace/{slug}/chats"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/chats")

    async def get_workspace_terminal_session_details(self, slug: str) -> Any:
        """Get workspace terminal session details.  GET /v1/workspace/{slug}/terminal-session-details"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/terminal-session-details")

    async def persist_workspace_terminal_ui_events(self, slug: str, body: dict | None = None) -> Any:
        """Persist terminal UI events.  POST /v1/workspace/{slug}/terminal-ui-events"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/terminal-ui-events", json=body)

    async def create_workspace_linked_terminal_message(self, slug: str, body: dict | None = None) -> Any:
        """Persist a linked terminal message.  POST /v1/workspace/{slug}/linked-terminal-message"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/linked-terminal-message", json=body)

    async def delete_workspace_chats(self, slug: str, body: dict | None = None) -> Any:
        """Delete selected workspace chats.  DELETE /v1/workspace/{slug}/delete-chats"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/delete-chats", json=body)

    async def delete_edited_workspace_chats(self, slug: str, body: dict | None = None) -> Any:
        """Delete edited workspace chats from a starting id.  DELETE /v1/workspace/{slug}/delete-edited-chats"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/delete-edited-chats", json=body)

    async def update_workspace_chat(self, slug: str, body: dict | None = None) -> Any:
        """Update a workspace chat response.  POST /v1/workspace/{slug}/update-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update-chat", json=body)

    async def update_workspace_chat_feedback(self, slug: str, chat_id: str, body: dict | None = None) -> Any:
        """Update workspace chat feedback.  POST /v1/workspace/{slug}/chat-feedback/{chatId}"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/chat-feedback/{chat_id}", json=body)

    async def get_workspace_suggested_messages(self, slug: str) -> Any:
        """Get suggested messages for a workspace.  GET /v1/workspace/{slug}/suggested-messages"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/suggested-messages")

    async def save_workspace_suggested_messages(self, slug: str, body: dict | None = None) -> Any:
        """Save suggested messages for a workspace.  POST /v1/workspace/{slug}/suggested-messages"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/suggested-messages", json=body)

    async def update_workspace_document_pin(self, slug: str, body: dict | None = None) -> Any:
        """Update workspace document pin status.  POST /v1/workspace/{slug}/update-pin"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update-pin", json=body)

    async def get_workspace_chat_tts(self, slug: str, chat_id: str) -> Any:
        """Generate text-to-speech audio for a workspace chat.  GET /v1/workspace/{slug}/tts/{chatId}"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/tts/{chat_id}")

    async def get_workspace_profile_picture(self, slug: str) -> Any:
        """Get a workspace profile picture.  GET /v1/workspace/{slug}/pfp"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/pfp")

    # @upload-stub — multipart upload
    async def upload_workspace_profile_picture(self, slug: str, files: dict) -> Any:
        """Upload a workspace profile picture.  POST /v1/workspace/{slug}/upload-pfp"""
        return await self._client.request_multipart("POST", f"/v1/workspace/{slug}/upload-pfp", files=files)

    async def remove_workspace_profile_picture(self, slug: str) -> Any:
        """Remove a workspace profile picture.  DELETE /v1/workspace/{slug}/remove-pfp"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/remove-pfp")

    async def fork_thread(self, slug: str, body: dict | None = None) -> Any:
        """Fork the workspace default thread.  POST /v1/workspace/{slug}/thread/fork"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/thread/fork", json=body)

    async def hide_workspace_chat(self, id: str) -> Any:
        """Hide a workspace chat.  PUT /v1/workspace/workspace-chats/{id}"""
        return await self._client.request("PUT", f"/v1/workspace/workspace-chats/{id}")

    # @upload-stub — multipart upload
    async def upload_and_embed_workspace_document(self, slug: str, files: dict) -> Any:
        """Upload and embed a document.  POST /v1/workspace/{slug}/upload-and-embed"""
        return await self._client.request_multipart("POST", f"/v1/workspace/{slug}/upload-and-embed", files=files)

    async def remove_and_unembed_workspace_document(self, slug: str, body: dict | None = None) -> Any:
        """Remove and unembed a document.  DELETE /v1/workspace/{slug}/remove-and-unembed"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/remove-and-unembed", json=body)

    async def get_workspace_prompt_history(self, slug: str) -> Any:
        """Get workspace prompt history.  GET /v1/workspace/{slug}/prompt-history"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/prompt-history")

    async def delete_workspace_prompt_history(self, slug: str) -> Any:
        """Clear workspace prompt history.  DELETE /v1/workspace/{slug}/prompt-history"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/prompt-history")

    async def delete_workspace_prompt_history_entry(self, slug: str, id: str) -> Any:
        """Delete a workspace prompt history entry.  DELETE /v1/workspace/{slug}/prompt-history/{id}"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}/prompt-history/{id}")

    async def validate_workspace_search_provider(self, slug: str, body: dict | None = None) -> Any:
        """Validate search provider configuration.  POST /v1/workspace/{slug}/search/validate"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/search/validate", json=body)
