# AUTO-GENERATED from openapi.json — do not edit this file directly.
# Re-run: node scripts/generate-v1-sdk.mjs
# Spec digest: d26c575c09f9951f
# Tag: Workspaces

from __future__ import annotations
from typing import Any, Optional
from .client import DeveloperApiClient


class V1WorkspaceModule:
    def __init__(self, client: DeveloperApiClient) -> None:
        self._client = client

    async def create_workspace(self, body: dict | None = None) -> Any:
        """Create a new workspace  POST /v1/workspace/new"""
        return await self._client.request("POST", "/v1/workspace/new", json=body)

    async def list_workspaces(self) -> Any:
        """List all current workspaces  GET /v1/workspaces"""
        return await self._client.request("GET", "/v1/workspaces")

    async def get_workspace(self, slug: str) -> Any:
        """Get a workspace by its unique slug.  GET /v1/workspace/{slug}"""
        return await self._client.request("GET", f"/v1/workspace/{slug}")

    async def delete_workspace(self, slug: str) -> Any:
        """Deletes a workspace by its slug.  DELETE /v1/workspace/{slug}"""
        return await self._client.request("DELETE", f"/v1/workspace/{slug}")

    async def update_workspace(self, slug: str, body: dict | None = None) -> Any:
        """Update workspace settings by its unique slug.  POST /v1/workspace/{slug}/update"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update", json=body)

    async def list_chats(self, slug: str) -> Any:
        """Get a workspaces chats regardless of user by its unique slug.  GET /v1/workspace/{slug}/chats"""
        return await self._client.request("GET", f"/v1/workspace/{slug}/chats")

    async def update_embeddings(self, slug: str, body: dict | None = None) -> Any:
        """Add or remove documents from a workspace by its unique slug.  POST /v1/workspace/{slug}/update-embeddings"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update-embeddings", json=body)

    async def update_pin(self, slug: str, body: dict | None = None) -> Any:
        """Add or remove pin from a document in a workspace by its unique slug.  POST /v1/workspace/{slug}/update-pin"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/update-pin", json=body)

    async def chat(self, slug: str, body: dict | None = None) -> Any:
        """Execute a chat with a workspace  POST /v1/workspace/{slug}/chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/chat", json=body)

    # @streaming-stub — implement SSE parsing in overrides/v1_workspace_streaming.py
    async def stream_chat(self, slug: str, body: dict | None = None) -> Any:
        """Execute a streamable chat with a workspace  POST /v1/workspace/{slug}/stream-chat"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/stream-chat", json=body)

    async def vector_search(self, slug: str, body: dict | None = None) -> Any:
        """Perform a vector similarity search in a workspace  POST /v1/workspace/{slug}/vector-search"""
        return await self._client.request("POST", f"/v1/workspace/{slug}/vector-search", json=body)
