'use strict';
/**
 * sdk-init.js — Developer Mode SDK initializer
 * AUTO-GENERATED by scripts/generate-skill.mjs — do not edit by hand.
 *
 * Source reference: typescript/src/index.ts (RealtimeXSDK constructor)
 * API key priority:
 *   1. explicit override passed to initSDK()
 *   2. REALTIMEX_API_KEY / REALTIMEX_AI_API_KEY in <envDir>/.env
 *   3. RTX_API_KEY / REALTIMEX_API_KEY / REALTIMEX_AI_API_KEY in process.env
 *   4. Interactive readline prompt
 */

const path = require('path');
const fs   = require('fs');
const readline = require('readline');

const ALL_PERMISSIONS = [
  'api.agents', 'api.workspaces', 'api.threads', 'api.task',
  'webhook.trigger', 'activities.read', 'activities.write',
  'llm.chat', 'llm.embed', 'llm.providers',
  'vectors.read', 'vectors.write',
  'tts.generate', 'mcp.servers', 'mcp.tools', 'acp.agent',
];

function parseEnvFile(filePath) {
  const vars = {};
  if (!fs.existsSync(filePath)) return vars;
  for (const raw of fs.readFileSync(filePath, 'utf-8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const val = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    vars[key] = val;
  }
  return vars;
}

async function resolveApiKey({ envDir, apiKey } = {}) {
  if (apiKey) return apiKey;
  const envVars = parseEnvFile(path.join(envDir || process.cwd(), '.env'));
  const fromFile = envVars.REALTIMEX_API_KEY || envVars.REALTIMEX_AI_API_KEY;
  if (fromFile) return fromFile;
  const fromEnv = process.env.RTX_API_KEY || process.env.REALTIMEX_API_KEY || process.env.REALTIMEX_AI_API_KEY;
  if (fromEnv) return fromEnv;
  const rl = readline.createInterface({ input: process.stdin, output: process.stderr });
  return new Promise((resolve) => {
    rl.question('RealTimeX API key not found. Enter your API key: ', (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function initSDK(opts = {}) {
  const { RealtimeXSDK } = require('@realtimex/sdk');
  const apiKey = await resolveApiKey(opts);
  if (!apiKey) throw new Error('No API key found. Set REALTIMEX_API_KEY in .env or provide it interactively.');
  const sdk = new RealtimeXSDK({
    realtimex: { url: opts.url || 'http://localhost:3001', apiKey },
    permissions: opts.permissions || ALL_PERMISSIONS,
  });
  return { sdk, apiKey };
}

module.exports = { initSDK, resolveApiKey, parseEnvFile, ALL_PERMISSIONS };
