'use strict';
/**
 * sdk-init.js — SDK initializer
 * AUTO-GENERATED by scripts/generate-skill.mjs — do not edit by hand.
 *
 * Credential resolution:
 *   1. Explicit override passed to initSDK({ apiKey } or { appId })
 *   2. ~/.realtimex.ai/.sdk-app-id file (written by RealtimeX server)
 *   3. RTX_APP_ID in process.env (injected by RealtimeX for local apps)
 *   4. RTX_API_KEY in process.env (standalone dev)
 *   5. REALTIMEX_API_KEY / REALTIMEX_AI_API_KEY in <envDir>/.env (standalone dev)
 *   6. Interactive readline prompt (fallback)
 */

const path = require('path');
const fs   = require('fs');
const os   = require('os');
const readline = require('readline');

const ALL_PERMISSIONS = [
  'api.agents', 'api.workspaces', 'api.threads', 'api.task',
  'webhook.trigger', 'activities.read', 'activities.write',
  'llm.chat', 'llm.embed', 'llm.providers',
  'vectors.read', 'vectors.write',
  'tts.generate', 'mcp.servers', 'mcp.tools', 'acp.agent',
];

/** Well-known file written by RealtimeX server for seamless auth. */
const SDK_APP_ID_FILE = path.join(os.homedir(), '.realtimex.ai', '.sdk-app-id');

function parseEnvFile(filePath) {
  const vars = {};
  if (!fs.existsSync(filePath)) return vars;
  for (const raw of fs.readFileSync(filePath, 'utf-8').split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const val = line.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    vars[key] = val;
  }
  return vars;
}

/**
 * Resolve credentials. The well-known app ID file is checked first so
 * agents running inside RealtimeX authenticate without hitting stale
 * or inherited env vars.
 */
async function resolveCredentials({ envDir, apiKey, appId } = {}) {
  // 1. Explicit overrides
  if (apiKey) return { apiKey, appId: null };
  if (appId) return { apiKey: null, appId };

  // 2. Well-known file (written by RealtimeX server — highest auto priority)
  try {
    if (fs.existsSync(SDK_APP_ID_FILE)) {
      const fileAppId = fs.readFileSync(SDK_APP_ID_FILE, 'utf-8').trim();
      if (fileAppId) return { apiKey: null, appId: fileAppId };
    }
  } catch { /* ignore read errors */ }

  // 3. RTX_APP_ID from process.env (injected by Electron for local apps)
  const envAppId = process.env.RTX_APP_ID;
  if (envAppId) return { apiKey: null, appId: envAppId };

  // 4. RTX_API_KEY from process.env (standalone dev — explicit, no collision risk)
  if (process.env.RTX_API_KEY) return { apiKey: process.env.RTX_API_KEY, appId: null };

  // 5. .env file (standalone dev)
  const envVars = parseEnvFile(path.join(envDir || process.cwd(), '.env'));
  const fromFile = envVars.RTX_API_KEY || envVars.REALTIMEX_API_KEY || envVars.REALTIMEX_AI_API_KEY;
  if (fromFile) return { apiKey: fromFile, appId: null };

  // 6. Interactive prompt (fallback)
  const rl = readline.createInterface({ input: process.stdin, output: process.stderr });
  const answer = await new Promise((resolve) => {
    rl.question('RealTimeX API key not found. Enter your API key: ', (ans) => {
      rl.close();
      resolve(ans.trim());
    });
  });
  if (answer) return { apiKey: answer, appId: null };

  return { apiKey: null, appId: null };
}

async function initSDK(opts = {}) {
  const { RealtimeXSDK } = require('@realtimex/sdk');
  const { apiKey, appId } = await resolveCredentials(opts);

  if (!apiKey && !appId) {
    throw new Error(
      'No credentials found. Run inside RealtimeX for automatic auth, or set RTX_API_KEY.'
    );
  }

  const sdk = new RealtimeXSDK({
    realtimex: {
      url: opts.url || 'http://localhost:3001',
      ...(apiKey ? { apiKey } : {}),
      ...(appId ? { appId } : {}),
    },
    permissions: opts.permissions || ALL_PERMISSIONS,
  });

  return { sdk, apiKey: apiKey || null, appId: appId || null };
}

module.exports = { initSDK, resolveCredentials, parseEnvFile, ALL_PERMISSIONS, SDK_APP_ID_FILE };